<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OverloadParty.GameDesignConstants" Version="0.1.5" />
    <ProjectReference Include="..\..\packages\game-logic-constants-dotnet\OverloadParty.GameLogicConstants.csproj" />
    <ProjectReference Include="..\..\packages\game-state-dotnet\OverloadParty.GameState.csproj" />
  </ItemGroup>

</Project>
