//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace OverloadParty.GameState
{
    using System = global::System;

    

    /// <summary>
    /// クライアントに返すゲーム状態スナップショット。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ClientGameState
    {

        /// <summary>
        /// ゲーム ID (ULID)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("gameID")]
        public string GameID { get; set; } = default!;

        /// <summary>
        /// 現在のターン番号
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("currentTurn")]
        public long CurrentTurn { get; set; } = default!;

        /// <summary>
        /// 現在のフェーズ (`draw` / `main` / `battle` / `end`)。
        /// <br/>定数マッピングは data/game_logic_constants.yaml 参照。
        /// <br/>
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("currentPhase")]
        public string CurrentPhase { get; set; } = default!;

        /// <summary>
        /// アクティブプレイヤー番号 (1 or 2)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("activePlayer")]
        public long ActivePlayer { get; set; } = default!;

        /// <summary>
        /// 自分のターンか
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("isMyTurn")]
        public bool IsMyTurn { get; set; } = default!;

        /// <summary>
        /// ターン開始日時
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("turnStartedAt")]
        public System.DateTimeOffset TurnStartedAt { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("myView")]
        public PlayerView MyView { get; set; } = new PlayerView();

        [System.Text.Json.Serialization.JsonPropertyName("oppView")]
        public OpponentView OppView { get; set; } = new OpponentView();

        [System.Text.Json.Serialization.JsonPropertyName("player1Summary")]
        public PlayerSummary Player1Summary { get; set; } = new PlayerSummary();

        [System.Text.Json.Serialization.JsonPropertyName("player2Summary")]
        public PlayerSummary Player2Summary { get; set; } = new PlayerSummary();

        /// <summary>
        /// 効果処理中にプレイヤー選択が必要な状態。null なら待ちなし。chooser は availableActions の候補から 1 件を選び resolve_pending_choice アクションで送信する。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pendingEffectChoice")]
        public PendingEffectChoiceView? PendingEffectChoice { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// pendingEffectChoice の client 公開ビュー。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PendingEffectChoiceView
    {

        /// <summary>
        /// 選択を行うプレイヤー番号
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("chooserPlayerNum")]
        public long ChooserPlayerNum { get; set; } = default!;

        /// <summary>
        /// 発動中の効果を持つカードの ID
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("effectCardId")]
        public string EffectCardId { get; set; } = default!;

        /// <summary>
        /// 発動中の効果を持つカードのインスタンス ID
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("effectInstanceId")]
        public string EffectInstanceId { get; set; } = default!;

        /// <summary>
        /// 選択対象の種別 (hand_card / field_target / deck_top / branch / face_down_reactive)。選択肢の提示は resolve_pending_choice アクションの choiceOptions が担う。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("choiceKind")]
        public string ChoiceKind { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// 対戦当時の player の name と level の snapshot (battle 開始時点の値、試合中不変)。
    /// <br/>ClientGameState.player1Summary / player2Summary として client に pass-through される。
    /// <br/>NPC のように level を持たない player では level は null となる。
    /// <br/>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PlayerSummary
    {

        /// <summary>
        /// 表示名 snapshot
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// level snapshot (NPC など level を持たない player では null)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("level")]
        public long? Level { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// 自プレイヤー視点のスナップショット。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PlayerView
    {

        [System.Text.Json.Serialization.JsonPropertyName("playerNum")]
        public long PlayerNum { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("budget")]
        public long Budget { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("insightPool")]
        public long InsightPool { get; set; } = default!;

        /// <summary>
        /// タイムバンク (秒)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("timeBank")]
        public long TimeBank { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("field")]
        public Field Field { get; set; } = new Field();

        [System.Text.Json.Serialization.JsonPropertyName("hand")]
        public System.Collections.Generic.List<UndeployedCard> Hand { get; set; } = new System.Collections.Generic.List<UndeployedCard>();

        /// <summary>
        /// リポジトリ残り枚数
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("repoCount")]
        public int RepoCount { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("trashCount")]
        public int TrashCount { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("trash")]
        public System.Collections.Generic.List<UndeployedCard> Trash { get; set; } = new System.Collections.Generic.List<UndeployedCard>();

        /// <summary>
        /// 実行可能アクション一覧 (アクティブプレイヤーのみ)。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("availableActions")]
        public System.Collections.Generic.List<AvailableAction> AvailableActions { get; set; } = default!;

        /// <summary>
        /// 効果由来のスロット選択待ち。null なら待ちなし。MyView 視点のプレイヤー番号が選択対象のときだけ値を持つ。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pendingSlotSelect")]
        public PendingSlotSelectView? PendingSlotSelect { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// 効果からのリソースデプロイを待っているスロット選択の client 公開ビュー。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PendingSlotSelectView
    {

        /// <summary>
        /// 配置待ちのリソース。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("resource")]
        public DeployedResource Resource { get; set; } = new DeployedResource();

        /// <summary>
        /// 配置可能なゾーンとスロット ("frontend_0" 等)。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("validZones")]
        public System.Collections.Generic.List<string> ValidZones { get; set; } = new System.Collections.Generic.List<string>();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// 相手プレイヤー視点 (情報秘匿適用済み)。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class OpponentView
    {

        [System.Text.Json.Serialization.JsonPropertyName("playerNum")]
        public long PlayerNum { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("budget")]
        public long Budget { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("insightPool")]
        public long InsightPool { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("timeBank")]
        public long TimeBank { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("field")]
        public OpponentField Field { get; set; } = new OpponentField();

        /// <summary>
        /// 手札枚数 (内容は非公開)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("handCount")]
        public int HandCount { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("repoCount")]
        public int RepoCount { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("trashCount")]
        public int TrashCount { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("trash")]
        public System.Collections.Generic.List<UndeployedCard> Trash { get; set; } = new System.Collections.Generic.List<UndeployedCard>();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// 一方のプレイヤーのフィールド全体。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Field
    {

        /// <summary>
        /// フロントゾーン (3 スロット)、空き枠は null。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("frontend")]
        public System.Collections.Generic.List<DeployedResource?> Frontend { get; set; } = new System.Collections.Generic.List<DeployedResource?>();

        /// <summary>
        /// バックゾーン (3 スロット)、空き枠は null。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("backend")]
        public System.Collections.Generic.List<DeployedResource?> Backend { get; set; } = new System.Collections.Generic.List<DeployedResource?>();

        /// <summary>
        /// サポートゾーン (3 スロット)、空き枠は null。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("support")]
        public System.Collections.Generic.List<DeployedSupport?> Support { get; set; } = new System.Collections.Generic.List<DeployedSupport?>();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// 相手のフィールド (サポートは非公開カード隠蔽)。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class OpponentField
    {

        [System.Text.Json.Serialization.JsonPropertyName("frontend")]
        public System.Collections.Generic.List<DeployedResource?> Frontend { get; set; } = new System.Collections.Generic.List<DeployedResource?>();

        [System.Text.Json.Serialization.JsonPropertyName("backend")]
        public System.Collections.Generic.List<DeployedResource?> Backend { get; set; } = new System.Collections.Generic.List<DeployedResource?>();

        [System.Text.Json.Serialization.JsonPropertyName("support")]
        public System.Collections.Generic.List<HiddenDeployedSupport?> Support { get; set; } = new System.Collections.Generic.List<HiddenDeployedSupport?>();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// フィールドに展開済みのリソースカードインスタンス。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DeployedResource
    {

        [System.Text.Json.Serialization.JsonPropertyName("instanceID")]
        public string InstanceID { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("cardID")]
        public string CardID { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("artNo")]
        public long ArtNo { get; set; } = default!;

        /// <summary>
        /// ランク (S/M/L/XL)。game-design-constants の Rank に対応。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("rank")]
        public string? Rank { get; set; } = default!;

        /// <summary>
        /// インスタンスファミリー。game-design-constants の InstanceFamily に対応。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("instanceFamily")]
        public string? InstanceFamily { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("faceUp")]
        public bool FaceUp { get; set; } = default!;

        /// <summary>
        /// デプロイ残りターン数 (0=アクティブ)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("deployingTurnsLeft")]
        public long DeployingTurnsLeft { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("currentAV")]
        public long CurrentAV { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("maxAV")]
        public long MaxAV { get; set; } = default!;

        /// <summary>
        /// 現在のスループット (Compute のみ)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("currentTP")]
        public long? CurrentTP { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("maxTP")]
        public long? MaxTP { get; set; } = default!;

        /// <summary>
        /// 現在のイールド (Data のみ)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("currentYield")]
        public long? CurrentYield { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("maxYield")]
        public long? MaxYield { get; set; } = default!;

        /// <summary>
        /// 受けたダメージ量
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("damage")]
        public long Damage { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("temporaryEffects")]
        public System.Collections.Generic.List<TemporaryEffect> TemporaryEffects { get; set; } = new System.Collections.Generic.List<TemporaryEffect>();

        /// <summary>
        /// このターンに収益化へ使用済みか
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("monetizedThisTurn")]
        public bool MonetizedThisTurn { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("hasAttacked")]
        public bool HasAttacked { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("effectUsedThisTurn")]
        public bool EffectUsedThisTurn { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("effectUsedThisGame")]
        public bool EffectUsedThisGame { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("deployedOnTurn")]
        public long DeployedOnTurn { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("deployOrder")]
        public long DeployOrder { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("elasticBonus")]
        public long ElasticBonus { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("lastAttackTurn")]
        public long LastAttackTurn { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// フィールドに展開済みのサポートカードインスタンス。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DeployedSupport
    {

        [System.Text.Json.Serialization.JsonPropertyName("instanceID")]
        public string InstanceID { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("cardID")]
        public string CardID { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("artNo")]
        public long ArtNo { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("faceUp")]
        public bool FaceUp { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("deployingTurnsLeft")]
        public long DeployingTurnsLeft { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("deployOrder")]
        public long DeployOrder { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("effectUsedThisTurn")]
        public bool EffectUsedThisTurn { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("effectUsedThisGame")]
        public bool EffectUsedThisGame { get; set; } = default!;

        /// <summary>
        /// Attachment 対象のインスタンス ID
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("targetInstanceID")]
        public string? TargetInstanceID { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// 表向き情報を隠蔽したサポートインスタンス。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class HiddenDeployedSupport
    {

        [System.Text.Json.Serialization.JsonPropertyName("instanceID")]
        public string InstanceID { get; set; } = default!;

        /// <summary>
        /// カード ID (表向きの場合のみ含まれる)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("cardID")]
        public string? CardID { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("artNo")]
        public long ArtNo { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("faceDown")]
        public bool FaceDown { get; set; } = default!;

        /// <summary>
        /// 覗き見されたか
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("peeked")]
        public bool Peeked { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// 手札・トラッシュ等にあるカード。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UndeployedCard
    {

        [System.Text.Json.Serialization.JsonPropertyName("instanceID")]
        public string InstanceID { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("cardID")]
        public string CardID { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("artNo")]
        public long ArtNo { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// カードに付与されている一時効果。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TemporaryEffect
    {

        [System.Text.Json.Serialization.JsonPropertyName("effectType")]
        public string EffectType { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        public long Value { get; set; } = default!;

        /// <summary>
        /// 持続期間 (`until_end_of_turn` / `permanent` 等)。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("duration")]
        public string Duration { get; set; } = default!;

        /// <summary>
        /// 効果の発生源インスタンス ID
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("sourceID")]
        public string SourceID { get; set; } = default!;

        /// <summary>
        /// バフモード (空文字=flat / `percent`=割合)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("mode")]
        public string Mode { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// 現在のターン操作可否を表すメッセージ。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TurnControlsMessage
    {

        /// <summary>
        /// 現在のフェーズを終了できるか (main / battle フェーズで `true`)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("canEndPhase")]
        public bool CanEndPhase { get; set; } = default!;

        /// <summary>
        /// 手札破棄が必要な枚数 (end フェーズで手札 &gt; 6 枚の場合のみ &gt; 0)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("discardRequired")]
        public int DiscardRequired { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// プレイヤーが現ターンに実行可能なアクション 1 件。`type` がアクション種別
    /// <br/>(play_card / attack など) を示し、その種別に必要なフィールドだけを持つ。
    /// <br/>
    /// </summary>
    [JsonInheritanceConverter(typeof(AvailableAction), "type")]
    [JsonInheritanceAttribute("play_card", typeof(PlayCardAction))]
    [JsonInheritanceAttribute("attack", typeof(AttackAction))]
    [JsonInheritanceAttribute("scale_up", typeof(ScaleUpAction))]
    [JsonInheritanceAttribute("monetize", typeof(MonetizeAction))]
    [JsonInheritanceAttribute("use_ignition", typeof(UseIgnitionAction))]
    [JsonInheritanceAttribute("use_initiative", typeof(UseInitiativeAction))]
    [JsonInheritanceAttribute("resolve_pending_choice", typeof(ResolvePendingChoiceAction))]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AvailableAction
    {

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// 手札からカードをプレイする候補。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PlayCardAction : AvailableAction
    {

        [System.Text.Json.Serialization.JsonPropertyName("handInstanceID")]
        public string HandInstanceID { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("cardID")]
        public string CardID { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("validZones")]
        public System.Collections.Generic.List<string> ValidZones { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("validTargets")]
        public System.Collections.Generic.List<string> ValidTargets { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("effectTargetType")]
        public string EffectTargetType { get; set; } = default!;

    }

    /// <summary>
    /// フロントエンドのコンピュート系リソースで攻撃する候補。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AttackAction : AvailableAction
    {

        [System.Text.Json.Serialization.JsonPropertyName("sourceInstanceID")]
        public string SourceInstanceID { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("validTargets")]
        public System.Collections.Generic.List<string> ValidTargets { get; set; } = default!;

    }

    /// <summary>
    /// リソースをスケールアップする候補。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ScaleUpAction : AvailableAction
    {

        [System.Text.Json.Serialization.JsonPropertyName("sourceInstanceID")]
        public string SourceInstanceID { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("targetRank")]
        public string TargetRank { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("instanceFamily")]
        public string InstanceFamily { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("needsFamily")]
        public bool NeedsFamily { get; set; } = default!;

    }

    /// <summary>
    /// リソースで収益化する候補。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MonetizeAction : AvailableAction
    {

        [System.Text.Json.Serialization.JsonPropertyName("sourceInstanceID")]
        public string SourceInstanceID { get; set; } = default!;

        /// <summary>
        /// 1 回の収益化で割り当てられる上限 (実効スループット)。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("remainingCapacity")]
        public long RemainingCapacity { get; set; } = default!;

    }

    /// <summary>
    /// フィールド上のカードの起動効果を使用する候補。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UseIgnitionAction : AvailableAction
    {

        [System.Text.Json.Serialization.JsonPropertyName("cardID")]
        public string CardID { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("sourceInstanceID")]
        public string SourceInstanceID { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("validTargets")]
        public System.Collections.Generic.List<string> ValidTargets { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("effectTargetType")]
        public string EffectTargetType { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("requiredCount")]
        public int RequiredCount { get; set; } = default!;

    }

    /// <summary>
    /// 施策 (ルーチン / スペシャル) を使用する候補。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UseInitiativeAction : AvailableAction
    {

        [System.Text.Json.Serialization.JsonPropertyName("cardID")]
        public string CardID { get; set; } = default!;

        /// <summary>
        /// 施策の区分 (routine / special)。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("kind")]
        public string Kind { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("cost")]
        public long Cost { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("validTargets")]
        public System.Collections.Generic.List<string> ValidTargets { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("effectTargetType")]
        public string EffectTargetType { get; set; } = default!;

    }

    /// <summary>
    /// 効果処理中の選択を解決する 1 アクション。chosenId は choiceOptions[].key から選ぶ。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ResolvePendingChoiceAction : AvailableAction
    {

        /// <summary>
        /// 発動中の効果を持つカードの ID
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("effectCardId")]
        public string EffectCardId { get; set; } = default!;

        /// <summary>
        /// 選択対象の種別 (hand_card / field_target / deck_top / branch / face_down_reactive)。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("choiceKind")]
        public string ChoiceKind { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("choiceOptions")]
        public System.Collections.Generic.List<ChoiceOption> ChoiceOptions { get; set; } = default!;

        /// <summary>
        /// deck_top 選択で選択するプレイヤーにだけ開示するデッキ上端カード。各 instanceID が choiceOptions[].key に対応する。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("revealedDeckTop")]
        public System.Collections.Generic.List<UndeployedCard> RevealedDeckTop { get; set; } = default!;

    }

    /// <summary>
    /// 選択肢 1 件。key は解決時に返す識別子 (branch キー / カード・インスタンス ID)。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ChoiceOption
    {

        [System.Text.Json.Serialization.JsonPropertyName("key")]
        public string Key { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PlayCardEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("cardId")]
        public string CardId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("zone")]
        public string Zone { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("index")]
        public int Index { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("cancelled")]
        public bool? Cancelled { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AttachCardEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("cardId")]
        public string CardId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("targetId")]
        public string TargetId { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AttackEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("attackerId")]
        public string AttackerId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("targetId")]
        public string TargetId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("damage")]
        public long Damage { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("destroyed")]
        public bool Destroyed { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("slaPenalty")]
        public long? SlaPenalty { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("cancelled")]
        public bool? Cancelled { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ScaleUpEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("instanceId")]
        public string InstanceId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("targetRank")]
        public string TargetRank { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("instanceFamily")]
        public string InstanceFamily { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MonetizeEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("totalAmount")]
        public long TotalAmount { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DiscardHandEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("discardedCount")]
        public int DiscardedCount { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("discardedIds")]
        public System.Collections.Generic.List<string> DiscardedIds { get; set; } = new System.Collections.Generic.List<string>();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UseIgnitionEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("cardId")]
        public string CardId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("sourceId")]
        public string SourceId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("targetId")]
        public string TargetId { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UseInitiativeEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("productId")]
        public string ProductId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("initiativeId")]
        public string InitiativeId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("kind")]
        public string Kind { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("initiativeName")]
        public string InitiativeName { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("insightCost")]
        public long InsightCost { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PhaseChangeEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("previousPhase")]
        public string PreviousPhase { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("currentPhase")]
        public string CurrentPhase { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PhaseEndEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("phase")]
        public string Phase { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("needsDiscard")]
        public bool NeedsDiscard { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TurnEndEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("phase")]
        public string Phase { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("nextTurn")]
        public long NextTurn { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("activePlayer")]
        public long ActivePlayer { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("currentPhase")]
        public string CurrentPhase { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class BattleStartEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("match_type")]
        public string MatchType { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("my_name")]
        public string MyName { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("my_level")]
        public long MyLevel { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("opponent_name")]
        public string OpponentName { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("opponent_level")]
        public long OpponentLevel { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TurnStartEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("turn")]
        public long Turn { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("is_my_turn")]
        public bool IsMyTurn { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ReactiveRevealedEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("instanceId")]
        public string InstanceId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("cardId")]
        public string CardId { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SelectSlotEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("cardId")]
        public string CardId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("instanceId")]
        public string InstanceId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("zone")]
        public string Zone { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("index")]
        public int Index { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GameOverEventData
    {

        [System.Text.Json.Serialization.JsonPropertyName("winnerNum")]
        public long WinnerNum { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("winReason")]
        public string WinReason { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Interface, AllowMultiple = true)]
    internal class JsonInheritanceAttribute : System.Attribute
    {
        public JsonInheritanceAttribute(string key, System.Type type)
        {
            Key = key;
            Type = type;
        }

        public string Key { get; }

        public System.Type Type { get; }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    internal class JsonInheritanceConverterAttribute : System.Text.Json.Serialization.JsonConverterAttribute
    {
        public string DiscriminatorName { get; }

        public JsonInheritanceConverterAttribute(System.Type baseType, string discriminatorName = "discriminator")
            : base(typeof(JsonInheritanceConverter<>).MakeGenericType(baseType))
        {
            DiscriminatorName = discriminatorName;
        }
    }

    public class JsonInheritanceConverter<TBase> : System.Text.Json.Serialization.JsonConverter<TBase>
    {
        private readonly string _discriminatorName;

        public JsonInheritanceConverter()
        {
            var attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute<JsonInheritanceConverterAttribute>(typeof(TBase));
            _discriminatorName = attribute?.DiscriminatorName ?? "discriminator";
        }

        public JsonInheritanceConverter(string discriminatorName)
        {
            _discriminatorName = discriminatorName;
        }

        public string DiscriminatorName { get { return _discriminatorName; } }

        public override TBase Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
        {
            var document = System.Text.Json.JsonDocument.ParseValue(ref reader);
            var hasDiscriminator = document.RootElement.TryGetProperty(_discriminatorName, out var discriminator);
            var subtype = GetDiscriminatorType(document.RootElement, typeToConvert, hasDiscriminator ? discriminator.GetString() : null);

            var bufferWriter = new System.IO.MemoryStream();
            using (var writer = new System.Text.Json.Utf8JsonWriter(bufferWriter))
            {
                document.RootElement.WriteTo(writer);
            }

            return (TBase)System.Text.Json.JsonSerializer.Deserialize(bufferWriter.ToArray(), subtype, options);
        }

        public override void Write(System.Text.Json.Utf8JsonWriter writer, TBase value, System.Text.Json.JsonSerializerOptions options)
        {
            if (value != null)
            {
                writer.WriteStartObject();
                writer.WriteString(_discriminatorName, GetDiscriminatorValue(value.GetType()));

                var bytes = System.Text.Json.JsonSerializer.SerializeToUtf8Bytes((object)value, options);
                var document = System.Text.Json.JsonDocument.Parse(bytes);
                foreach (var property in document.RootElement.EnumerateObject())
                {
                    property.WriteTo(writer);
                }

                writer.WriteEndObject();
            }
            else
            {
                writer.WriteNullValue();
            }
        }

        public string GetDiscriminatorValue(System.Type type)
        {
            var jsonInheritanceAttributeDiscriminator = GetSubtypeDiscriminator(type);
            if (jsonInheritanceAttributeDiscriminator != null)
            {
                return jsonInheritanceAttributeDiscriminator;
            }

            return type.Name;
        }

        protected System.Type GetDiscriminatorType(System.Text.Json.JsonElement jObject, System.Type objectType, string discriminatorValue)
        {
            if (discriminatorValue != null)
            {
                var jsonInheritanceAttributeSubtype = GetObjectSubtype(objectType, discriminatorValue);
                if (jsonInheritanceAttributeSubtype != null)
                {
                    return jsonInheritanceAttributeSubtype;
                }

                if (objectType.Name == discriminatorValue)
                {
                    return objectType;
                }

                var typeName = objectType.Namespace + "." + discriminatorValue;
                var subtype = System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType).Assembly.GetType(typeName);
                if (subtype != null)
                {
                    return subtype;
                }
            }

            throw new System.InvalidOperationException("Could not find subtype of '" + objectType.Name + "' with discriminator '" + discriminatorValue + "'.");
        }

        private System.Type GetObjectSubtype(System.Type baseType, string discriminatorValue)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(baseType), true))
            {
                if (attribute.Key == discriminatorValue)
                    return attribute.Type;
            }

            return null;
        }

        private string GetSubtypeDiscriminator(System.Type objectType)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Type == objectType)
                    return attribute.Key;
            }

            return null;
        }
    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765
