/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ヘルスチェック (ClusterIP 内部のみ) */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/npc/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** NPC モデル一覧を取得 */
        get: operations["listNpcModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/npc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** NPC 対戦ゲームを作成 */
        post: operations["createNpcGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/pvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** PvP ゲームを作成 (Gateway → Battle) */
        post: operations["createPvpGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{gameId}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ゲームアクションを実行 */
        post: operations["processGameAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{gameId}/advance-npc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** NPC ターンを進行 (game_enter 後に Gateway が呼び出す) */
        post: operations["advanceNpcTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{gameId}/state/{playerNum}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** プレイヤー視点のゲーム状態を取得 */
        get: operations["getGameStateForPlayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{gameId}/controls/{playerNum}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ターンコントロール情報を取得 */
        get: operations["getTurnControlsForPlayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{gameId}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ゲームログを JSON 形式で取得 (リプレイ用) */
        get: operations["getGameLogJson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{gameId}/log/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ゲームログをテキスト形式で取得 */
        get: operations["getGameLogText"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** カード定義一覧を取得 (ローカル開発モードでのみ有効) */
        get: operations["listDevCards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        NpcModelsResponse: {
            models: components["schemas"]["NpcModelEntry"][];
        };
        NpcModelEntry: {
            model: string;
            faction: string;
            difficulty: string;
            display_name: string;
        };
        /** @description デッキスナップショット内の 1 枚のカード。 */
        BattleDeckCard: {
            card_id: string;
            /** Format: int64 */
            art_no: number;
        };
        /** @description NPC または PvP ゲーム作成時の battle server からの応答。 */
        GameCreatedResult: {
            game_id: string;
        };
        /** @description アクション処理後に battle server が emit する 1 件のゲームイベント。 */
        ActionEvent: {
            /** Format: int64 */
            sequence: number;
            event_type: string;
            /**
             * Format: int64
             * @description アクション元のスロット番号 (1 or 2)。system event (turn_start 等) では null。
             */
            player_num: number | null;
            /**
             * @description イベント種別固有の payload。Go / C# では opaque な map / JsonElement として扱い、
             *     event_type ごとに用意された EventData schema で再 unmarshal する。
             */
            event_data: {
                [key: string]: unknown;
            };
            /** @description イベント直後のゲーム状態スナップショット。`event_data` 同様 opaque。 */
            state: {
                [key: string]: unknown;
            };
        };
        /** @description ゲームアクション処理後に返される結果。 */
        ActionResult: {
            /** @description ゲーム終了フラグ */
            game_over: boolean;
            /**
             * Format: int64
             * @description 勝者プレイヤー番号 (1 or 2、未終了時は 0)
             */
            winning_player_num: number;
            /** @description 終了理由 (WinReasons enum の文字列、未終了時は空文字) */
            win_reason: string;
            /** @description true の場合、Gateway は AdvanceNpcTurn を呼んで次の NPC アクションを取得する必要がある。 */
            npc_pending: boolean;
            /** @description このアクションで発生したイベント列。 */
            events: components["schemas"]["ActionEvent"][];
        };
        /** @description POST /api/v1/games/npc のリクエスト body。 */
        NpcBattleRequest: {
            deck_cards: components["schemas"]["BattleDeckCard"][];
            /** @description デッキに設定されたルーチン施策の ID。 */
            routine_id: string;
            /** @description デッキに設定されたスペシャル施策の ID。 */
            special_id: string;
            npc_model: string;
            player1_summary: components["schemas"]["PlayerSummaryRequest"];
            player2_summary: components["schemas"]["PlayerSummaryRequest"];
        };
        /** @description POST /api/v1/games/pvp のリクエスト body。 */
        PvpBattleRequest: {
            deck1_cards: components["schemas"]["BattleDeckCard"][];
            /** @description デッキ 1 に設定されたルーチン施策の ID。 */
            deck1_routine_id: string;
            /** @description デッキ 1 に設定されたスペシャル施策の ID。 */
            deck1_special_id: string;
            deck2_cards: components["schemas"]["BattleDeckCard"][];
            /** @description デッキ 2 に設定されたルーチン施策の ID。 */
            deck2_routine_id: string;
            /** @description デッキ 2 に設定されたスペシャル施策の ID。 */
            deck2_special_id: string;
            player1_summary: components["schemas"]["PlayerSummaryRequest"];
            player2_summary: components["schemas"]["PlayerSummaryRequest"];
        };
        /**
         * @description CreatePvP / CreateNpc API で battle に渡す player の name と level の snapshot。
         *     battle は upstream (account 等) に依存せず、渡された値を player_summary テーブルに
         *     永続化する。NPC のように level を持たない player では level は null となる。
         */
        PlayerSummaryRequest: {
            /** @description 表示名 snapshot */
            name: string;
            /**
             * Format: int64
             * @description level snapshot (NPC など level を持たない player では null)
             */
            level?: number | null;
        };
        /** @description POST /api/v1/games/{gameId}/actions のリクエスト body。 */
        GameActionRequest: {
            /** Format: int64 */
            player_num: number;
            action_type: string;
            /** @description アクション固有の payload。サーバ側で action_type に応じて再パースされる。 */
            data: {
                [key: string]: unknown;
            };
        };
        /** @description 開発用エンドポイント (/api/dev/cards) が返すカード一覧の 1 件。 */
        DevCard: {
            cardId: string;
            cardName: string;
            faction: string;
            cardType: string;
        };
        /** @description クライアントに返すゲーム状態スナップショット。 */
        ClientGameState: {
            /** @description ゲーム ID (UUID v7) */
            gameID: string;
            /**
             * Format: int64
             * @description 現在のターン番号
             */
            currentTurn: number;
            /**
             * @description 現在のフェーズ (`selecting` / `draw` / `yield` / `main` / `battle` / `end`)。
             *     定数マッピングは data/game_logic_constants.yaml 参照。
             */
            currentPhase: string;
            /**
             * Format: int64
             * @description アクティブプレイヤー番号 (1 or 2)
             */
            activePlayer: number;
            /** @description 自分のターンか */
            isMyTurn: boolean;
            /**
             * Format: date-time
             * @description ターン開始日時
             */
            turnStartedAt: string;
            myView: components["schemas"]["PlayerView"];
            oppView: components["schemas"]["OpponentView"];
            player1Summary: components["schemas"]["PlayerSummary"];
            player2Summary: components["schemas"]["PlayerSummary"];
            /** @description 効果処理中にプレイヤー選択が必要な状態。null なら待ちなし。chooser は availableActions の候補から 1 件を選び resolve_pending_choice アクションで送信する。 */
            pendingEffectChoice?: components["schemas"]["PendingEffectChoiceView"];
        };
        /** @description pendingEffectChoice の client 公開ビュー。 */
        PendingEffectChoiceView: {
            /**
             * Format: int64
             * @description 選択を行うプレイヤー番号
             */
            chooserPlayerNum: number;
            /** @description 発動中の効果を持つカードの ID */
            effectCardId: string;
            /** @description 発動中の効果を持つカードのインスタンス ID */
            effectInstanceId: string;
            /** @description 選択対象の種別 (hand_card / field_target / deck_top)。選択肢の提示は resolve_pending_choice アクションの choiceOptions が担う。 */
            choiceKind: string;
        };
        /**
         * @description 対戦当時の player の name と level の snapshot (battle 開始時点の値、試合中不変)。
         *     ClientGameState.player1Summary / player2Summary として client に pass-through される。
         *     NPC のように level を持たない player では level は null となる。
         */
        PlayerSummary: {
            /** @description 表示名 snapshot */
            name: string;
            /**
             * Format: int64
             * @description level snapshot (NPC など level を持たない player では null)
             */
            level?: number | null;
        };
        /** @description 自プレイヤー視点のスナップショット。 */
        PlayerView: {
            /** Format: int64 */
            playerNum: number;
            /** Format: int64 */
            budget: number;
            /** Format: int64 */
            insightPool: number;
            /**
             * Format: int64
             * @description タイムバンク (秒)
             */
            timeBank: number;
            field: components["schemas"]["Field"];
            hand: components["schemas"]["UndeployedCard"][];
            /**
             * Format: int32
             * @description リポジトリ残り枚数
             */
            repoCount: number;
            /** Format: int32 */
            trashCount: number;
            trash: components["schemas"]["UndeployedCard"][];
            /** @description 実行可能アクション一覧 (アクティブプレイヤーのみ)。 */
            availableActions?: components["schemas"]["AvailableAction"][];
            /** @description 効果由来のスロット選択待ち。null なら待ちなし。MyView 視点のプレイヤー番号が選択対象のときだけ値を持つ。 */
            pendingSlotSelect?: components["schemas"]["PendingSlotSelectView"];
        };
        /** @description 効果からのリソースデプロイを待っているスロット選択の client 公開ビュー。 */
        PendingSlotSelectView: {
            /** @description 配置待ちのリソース。 */
            resource: components["schemas"]["DeployedResource"];
            /** @description 配置可能なゾーンとスロット ("frontend_0" 等)。 */
            validZones: string[];
        };
        /** @description 相手プレイヤー視点 (情報秘匿適用済み)。 */
        OpponentView: {
            /** Format: int64 */
            playerNum: number;
            /** Format: int64 */
            budget: number;
            /** Format: int64 */
            insightPool: number;
            /** Format: int64 */
            timeBank: number;
            field: components["schemas"]["OpponentField"];
            /**
             * Format: int32
             * @description 手札枚数 (内容は非公開)
             */
            handCount: number;
            /** Format: int32 */
            repoCount: number;
            /** Format: int32 */
            trashCount: number;
            trash: components["schemas"]["UndeployedCard"][];
        };
        /** @description 一方のプレイヤーのフィールド全体。 */
        Field: {
            /** @description フロントゾーン (3 スロット)、空き枠は null。 */
            frontend: components["schemas"]["DeployedResource"][];
            /** @description バックゾーン (3 スロット)、空き枠は null。 */
            backend: components["schemas"]["DeployedResource"][];
            /** @description サポートゾーン (3 スロット)、空き枠は null。 */
            support: components["schemas"]["DeployedSupport"][];
        };
        /** @description 相手のフィールド (サポートは非公開カード隠蔽)。 */
        OpponentField: {
            frontend: components["schemas"]["DeployedResource"][];
            backend: components["schemas"]["DeployedResource"][];
            support: components["schemas"]["HiddenDeployedSupport"][];
        };
        /** @description フィールドに展開済みのリソースカードインスタンス。 */
        DeployedResource: {
            instanceID: string;
            cardID: string;
            /** Format: int64 */
            artNo: number;
            /** @description ランク (S/M/L/XL)。game-design-constants の Rank に対応。 */
            rank?: string | null;
            /** @description インスタンスファミリー。game-design-constants の InstanceFamily に対応。 */
            instanceFamily?: string | null;
            faceUp: boolean;
            /**
             * Format: int64
             * @description デプロイ残りターン数 (0=アクティブ)
             */
            deployingTurnsLeft: number;
            /** Format: int64 */
            currentAV: number;
            /** Format: int64 */
            maxAV: number;
            /**
             * Format: int64
             * @description 現在のスループット (Compute のみ)
             */
            currentTP?: number | null;
            /** Format: int64 */
            maxTP?: number | null;
            /**
             * Format: int64
             * @description 現在のイールド (Data のみ)
             */
            currentYield?: number | null;
            /** Format: int64 */
            maxYield?: number | null;
            /**
             * Format: int64
             * @description 受けたダメージ量
             */
            damage: number;
            temporaryEffects: components["schemas"]["TemporaryEffect"][];
            /**
             * Format: int64
             * @description 収益化で配分された Insight 量
             */
            monetizedAmount: number;
            hasAttacked: boolean;
            effectUsedThisTurn: boolean;
            effectUsedThisGame: boolean;
            /** Format: int64 */
            deployedOnTurn: number;
            /** Format: int64 */
            deployOrder: number;
            /** Format: int64 */
            elasticBonus: number;
            /** Format: int64 */
            lastAttackTurn: number;
        };
        /** @description フィールドに展開済みのサポートカードインスタンス。 */
        DeployedSupport: {
            instanceID: string;
            cardID: string;
            /** Format: int64 */
            artNo: number;
            faceUp: boolean;
            /** Format: int64 */
            deployingTurnsLeft: number;
            /** Format: int64 */
            deployOrder: number;
            effectUsedThisTurn: boolean;
            effectUsedThisGame: boolean;
            /** @description Attachment 対象のインスタンス ID */
            targetInstanceID?: string | null;
        };
        /** @description 表向き情報を隠蔽したサポートインスタンス。 */
        HiddenDeployedSupport: {
            instanceID: string;
            /** @description カード ID (表向きの場合のみ含まれる) */
            cardID?: string | null;
            /** Format: int64 */
            artNo: number;
            faceDown: boolean;
            /** @description 覗き見されたか */
            peeked: boolean;
        };
        /** @description 手札・トラッシュ等にあるカード。 */
        UndeployedCard: {
            instanceID: string;
            cardID: string;
            /** Format: int64 */
            artNo: number;
        };
        /** @description カードに付与されている一時効果。 */
        TemporaryEffect: {
            effectType: string;
            /** Format: int64 */
            value: number;
            /** @description 持続期間 (`until_end_of_turn` / `permanent` 等)。 */
            duration: string;
            /** @description 効果の発生源インスタンス ID */
            sourceID: string;
            /** @description バフモード (空文字=flat / `percent`=割合) */
            mode: string;
        };
        /** @description 現在のターン操作可否を表すメッセージ。 */
        TurnControlsMessage: {
            /** @description 現在のフェーズを終了できるか (main / battle フェーズで `true`) */
            canEndPhase: boolean;
            /**
             * Format: int32
             * @description 手札破棄が必要な枚数 (end フェーズで手札 > 6 枚の場合のみ > 0)
             */
            discardRequired: number;
        };
        /**
         * @description プレイヤーが現ターンに実行可能なアクション 1 件。`type` がアクション種別
         *     (play_card / attack など) を示し、その種別に必要なフィールドだけを持つ。
         */
        AvailableAction: {
            type: string;
        };
        /** @description 手札からカードをプレイする候補。 */
        PlayCardAction: Omit<components["schemas"]["AvailableAction"], "type"> & {
            handInstanceID?: string;
            cardID?: string;
            validZones?: string[];
            validTargets?: string[];
            effectTargetType?: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "play_card";
        };
        /** @description フロントエンドのコンピュート系リソースで攻撃する候補。 */
        AttackAction: Omit<components["schemas"]["AvailableAction"], "type"> & {
            sourceInstanceID?: string;
            validTargets?: string[];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "attack";
        };
        /** @description リソースをスケールアップする候補。 */
        ScaleUpAction: Omit<components["schemas"]["AvailableAction"], "type"> & {
            sourceInstanceID?: string;
            targetRank?: string;
            instanceFamily?: string;
            needsFamily?: boolean;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "scale_up";
        };
        /** @description リソースで収益化する候補。 */
        MonetizeAction: Omit<components["schemas"]["AvailableAction"], "type"> & {
            sourceInstanceID?: string;
            /** Format: int64 */
            remainingCapacity?: number;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "monetize";
        };
        /** @description フィールド上のカードの起動効果を使用する候補。 */
        UseIgnitionAction: Omit<components["schemas"]["AvailableAction"], "type"> & {
            cardID?: string;
            sourceInstanceID?: string;
            validTargets?: string[];
            effectTargetType?: string;
            /** Format: int32 */
            requiredCount?: number;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "use_ignition";
        };
        /** @description 施策 (ルーチン / スペシャル) を使用する候補。 */
        UseInitiativeAction: Omit<components["schemas"]["AvailableAction"], "type"> & {
            cardID?: string;
            /** @description 施策の区分 (routine / special)。 */
            kind?: string;
            /** Format: int64 */
            cost?: number;
            validTargets?: string[];
            effectTargetType?: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "use_initiative";
        };
        /** @description 効果処理中の選択を解決する 1 アクション。chosenId は choiceOptions[].key から選ぶ。 */
        ResolvePendingChoiceAction: Omit<components["schemas"]["AvailableAction"], "type"> & {
            /** @description 発動中の効果を持つカードの ID */
            effectCardId?: string;
            /** @description 選択対象の種別 (hand_card / field_target / deck_top)。 */
            choiceKind?: string;
            choiceOptions?: components["schemas"]["ChoiceOption"][];
            /** @description deck_top 選択で選択するプレイヤーにだけ開示するデッキ上端カード。各 instanceID が choiceOptions[].key に対応する。 */
            revealedDeckTop?: components["schemas"]["UndeployedCard"][];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "resolve_pending_choice";
        };
        /** @description 選択肢 1 件。key は解決時に返す識別子 (branch キー / カード・インスタンス ID)。 */
        ChoiceOption: {
            key: string;
        };
        PlayCardEventData: {
            cardId: string;
            zone: string;
            /** Format: int32 */
            index: number;
            cancelled?: boolean | null;
        };
        AttachCardEventData: {
            cardId: string;
            targetId: string;
        };
        AttackEventData: {
            attackerId: string;
            targetId: string;
            /** Format: int64 */
            damage: number;
            destroyed: boolean;
            /** Format: int64 */
            slaPenalty?: number | null;
            cancelled?: boolean | null;
        };
        ScaleUpEventData: {
            instanceId: string;
            targetRank: string;
            instanceFamily?: string;
        };
        MonetizeEventData: {
            /** Format: int64 */
            totalAmount: number;
        };
        DiscardHandEventData: {
            /** Format: int32 */
            discardedCount: number;
            discardedIds: string[];
        };
        UseIgnitionEventData: {
            cardId: string;
            sourceId: string;
            targetId?: string;
        };
        UseInitiativeEventData: {
            productId: string;
            initiativeId: string;
            kind: string;
            initiativeName: string;
            /** Format: int64 */
            insightCost: number;
        };
        PhaseChangeEventData: {
            previousPhase: string;
            currentPhase: string;
        };
        PhaseEndEventData: {
            phase: string;
            needsDiscard: boolean;
        };
        TurnEndEventData: {
            phase: string;
            /** Format: int64 */
            nextTurn: number;
            /** Format: int64 */
            activePlayer: number;
            currentPhase: string;
        };
        BattleStartEventData: {
            match_type: string;
            my_name: string;
            /** Format: int64 */
            my_level: number;
            opponent_name: string;
            /** Format: int64 */
            opponent_level: number;
        };
        TurnStartEventData: {
            /** Format: int64 */
            turn: number;
            is_my_turn: boolean;
        };
        ReactiveRevealedEventData: {
            instanceId: string;
            cardId: string;
        };
        SelectSlotEventData: {
            cardId: string;
            instanceId: string;
            zone: string;
            /** Format: int32 */
            index: number;
        };
        GameOverEventData: {
            /** Format: int64 */
            winnerNum: number;
            winReason: string;
        };
    };
    responses: never;
    parameters: {
        GameIdPath: string;
        PlayerNumPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listNpcModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NPC モデル一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NpcModelsResponse"];
                };
            };
        };
    };
    createNpcGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NpcBattleRequest"];
            };
        };
        responses: {
            /** @description 作成成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameCreatedResult"];
                };
            };
            /** @description デッキカードが不正、または NPC モデルが存在しない */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createPvpGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PvpBattleRequest"];
            };
        };
        responses: {
            /** @description 作成成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameCreatedResult"];
                };
            };
            /** @description デッキカードが不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    processGameAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameActionRequest"];
            };
        };
        responses: {
            /** @description アクション処理成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResult"];
                };
            };
            /** @description ルール違反 (GameRuleException) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    advanceNpcTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ターン進行成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResult"];
                };
            };
            /** @description ルール違反 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGameStateForPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameIdPath"];
                playerNum: components["parameters"]["PlayerNumPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ゲーム状態 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientGameState"];
                };
            };
            /** @description ゲームが存在しないか内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTurnControlsForPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameIdPath"];
                playerNum: components["parameters"]["PlayerNumPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ターンコントロール情報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnControlsMessage"];
                };
            };
            /** @description ゲームが存在しないか内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGameLogJson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ログ JSON (構造はバージョン非互換のため自由形式) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description ゲームが見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGameLogText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ログテキスト */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description ゲームが見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDevCards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description カード一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevCard"][];
                };
            };
        };
    };
}
