//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace OverloadParty.ApiBattleRpc
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class HealthResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string Status { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class NpcModelsResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("models")]
        public System.Collections.Generic.List<NpcModelEntry> Models { get; set; } = new System.Collections.Generic.List<NpcModelEntry>();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class NpcModelEntry
    {

        [System.Text.Json.Serialization.JsonPropertyName("model")]
        public string Model { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("faction")]
        public string Faction { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("difficulty")]
        public string Difficulty { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("display_name")]
        public string DisplayName { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// デッキスナップショット内の 1 枚のカード。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class BattleDeckCard
    {

        [System.Text.Json.Serialization.JsonPropertyName("card_id")]
        public string CardId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("art_no")]
        public long ArtNo { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// NPC または PvP ゲーム作成時の battle server からの応答。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GameCreatedResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("game_id")]
        public string GameId { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// アクション処理後に battle server が emit する 1 件のゲームイベント。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ActionEvent
    {

        [System.Text.Json.Serialization.JsonPropertyName("sequence")]
        public long Sequence { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("event_type")]
        public string EventType { get; set; } = default!;

        /// <summary>
        /// アクション元のスロット番号 (1 or 2)。system event (turn_start 等) では null。
        /// <br/>
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("player_num")]
        public long? PlayerNum { get; set; } = default!;

        /// <summary>
        /// イベント種別固有の payload。Go / C# では opaque な map / JsonElement として扱い、
        /// <br/>event_type ごとに用意された EventData schema で再 unmarshal する。
        /// <br/>
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("event_data")]
        public System.Text.Json.JsonElement EventData { get; set; } = new System.Text.Json.JsonElement();

        /// <summary>
        /// イベント直後のゲーム状態スナップショット。`event_data` 同様 opaque。
        /// <br/>
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("state")]
        public System.Text.Json.JsonElement State { get; set; } = new System.Text.Json.JsonElement();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// ゲームアクション処理後に返される結果。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ActionResult
    {

        /// <summary>
        /// ゲーム終了フラグ
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("game_over")]
        public bool GameOver { get; set; } = default!;

        /// <summary>
        /// 勝者プレイヤー番号 (1 or 2、未終了時は 0)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("winning_player_num")]
        public long WinningPlayerNum { get; set; } = default!;

        /// <summary>
        /// 終了理由 (WinReasons enum の文字列、未終了時は空文字)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("win_reason")]
        public string WinReason { get; set; } = default!;

        /// <summary>
        /// true の場合、Gateway は AdvanceNpcTurn を呼んで次の NPC アクションを取得する必要がある。
        /// <br/>
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("npc_pending")]
        public bool NpcPending { get; set; } = default!;

        /// <summary>
        /// このアクションで発生したイベント列。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("events")]
        public System.Collections.Generic.List<ActionEvent> Events { get; set; } = new System.Collections.Generic.List<ActionEvent>();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// POST /api/v1/games/npc のリクエスト body。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class NpcBattleRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("deck_cards")]
        public System.Collections.Generic.List<BattleDeckCard> DeckCards { get; set; } = new System.Collections.Generic.List<BattleDeckCard>();

        /// <summary>
        /// デッキに設定されたルーチン施策の ID。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("routine_id")]
        public string RoutineId { get; set; } = default!;

        /// <summary>
        /// デッキに設定されたスペシャル施策の ID。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("special_id")]
        public string SpecialId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("npc_model")]
        public string NpcModel { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("player1_summary")]
        public PlayerSummaryRequest Player1Summary { get; set; } = new PlayerSummaryRequest();

        [System.Text.Json.Serialization.JsonPropertyName("player2_summary")]
        public PlayerSummaryRequest Player2Summary { get; set; } = new PlayerSummaryRequest();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// POST /api/v1/games/pvp のリクエスト body。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PvpBattleRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("deck1_cards")]
        public System.Collections.Generic.List<BattleDeckCard> Deck1Cards { get; set; } = new System.Collections.Generic.List<BattleDeckCard>();

        /// <summary>
        /// デッキ 1 に設定されたルーチン施策の ID。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("deck1_routine_id")]
        public string Deck1RoutineId { get; set; } = default!;

        /// <summary>
        /// デッキ 1 に設定されたスペシャル施策の ID。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("deck1_special_id")]
        public string Deck1SpecialId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("deck2_cards")]
        public System.Collections.Generic.List<BattleDeckCard> Deck2Cards { get; set; } = new System.Collections.Generic.List<BattleDeckCard>();

        /// <summary>
        /// デッキ 2 に設定されたルーチン施策の ID。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("deck2_routine_id")]
        public string Deck2RoutineId { get; set; } = default!;

        /// <summary>
        /// デッキ 2 に設定されたスペシャル施策の ID。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("deck2_special_id")]
        public string Deck2SpecialId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("player1_summary")]
        public PlayerSummaryRequest Player1Summary { get; set; } = new PlayerSummaryRequest();

        [System.Text.Json.Serialization.JsonPropertyName("player2_summary")]
        public PlayerSummaryRequest Player2Summary { get; set; } = new PlayerSummaryRequest();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// CreatePvP / CreateNpc API で battle に渡す player の name と level の snapshot。
    /// <br/>battle は upstream (account 等) に依存せず、渡された値を player_summary テーブルに
    /// <br/>永続化する。NPC のように level を持たない player では level は null となる。
    /// <br/>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PlayerSummaryRequest
    {

        /// <summary>
        /// 表示名 snapshot
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// level snapshot (NPC など level を持たない player では null)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("level")]
        public long? Level { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// POST /api/v1/games/{gameId}/actions のリクエスト body。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GameActionRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("player_num")]
        public long PlayerNum { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("action_type")]
        public string ActionType { get; set; } = default!;

        /// <summary>
        /// アクション固有の payload。サーバ側で action_type に応じて再パースされる。
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public System.Text.Json.JsonElement Data { get; set; } = new System.Text.Json.JsonElement();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// 開発用エンドポイント (/api/dev/cards) が返すカード一覧の 1 件。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DevCard
    {

        [System.Text.Json.Serialization.JsonPropertyName("cardId")]
        public string CardId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("cardName")]
        public string CardName { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("faction")]
        public string Faction { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("cardType")]
        public string CardType { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765
