using OverloadParty.Battle.Models;

namespace OverloadParty.Battle.Engine;

/// <summary>
/// Represents a game-over outcome with the winner and reason.
/// WinnerNum=0 means draw.
/// </summary>
public record GameOverResult(long WinnerNum, string Reason);

/// <summary>
/// ActionResult はアクション処理または自動進行の結果を表現します
/// </summary>
public class ActionResult
{
    /// <summary>Events generated by this action (broadcast to clients).</summary>
    public List<GameEvent> Events { get; set; } = [];

    /// <summary>Non-null if the game ended as a result of this action.</summary>
    public GameOverResult? GameOver { get; set; }

    /// <summary>Whether the active player must discard before the turn can end.</summary>
    public bool ShouldDiscard { get; set; }

    /// <summary>Whether the player must select a deployment slot before any other action.</summary>
    public bool ShouldSelectSlot { get; set; }
}
