<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OverloadParty.Battle.Models\OverloadParty.Battle.Models.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OverloadParty.GameDesignConstants" Version="0.1.2" />
    <PackageReference Include="OverloadParty.GameLogicConstants" Version="0.1.0" />
    <PackageReference Include="OverloadParty.GameState" Version="0.1.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OverloadParty.Battle.Tests" />
  </ItemGroup>

</Project>
