// Package apibattle provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apibattle

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// ActionEvent アクション処理後に battle server が emit する 1 件のゲームイベント。
type ActionEvent struct {
	// EventData イベント種別固有の payload。Go / C# では opaque な map / JsonElement として扱い、
	// event_type ごとに用意された EventData schema で再 unmarshal する。
	EventData map[string]interface{} `json:"event_data"`
	EventType string                 `json:"event_type"`

	// PlayerNum アクション元のスロット番号 (1 or 2)。system event (turn_start 等) では null。
	PlayerNum *int64 `json:"player_num"`
	Sequence  int64  `json:"sequence"`

	// State イベント直後のゲーム状態スナップショット。`event_data` 同様 opaque。
	State map[string]interface{} `json:"state"`
}

// ActionResult ゲームアクション処理後に返される結果。
type ActionResult struct {
	// Events このアクションで発生したイベント列。
	Events []ActionEvent `json:"events"`

	// GameOver ゲーム終了フラグ
	GameOver bool `json:"game_over"`

	// NpcPending true の場合、Gateway は AdvanceNpcTurn を呼んで次の NPC アクションを取得する必要がある。
	NpcPending bool `json:"npc_pending"`

	// WinReason 終了理由 (WinReasons enum の文字列、未終了時は空文字)
	WinReason string `json:"win_reason"`

	// WinningPlayerNum 勝者プレイヤー番号 (1 or 2、未終了時は 0)
	WinningPlayerNum int64 `json:"winning_player_num"`
}

// AttachCardEventData defines model for AttachCardEventData.
type AttachCardEventData struct {
	CardId   string `json:"cardId"`
	TargetId string `json:"targetId"`
}

// AttackAction defines model for AttackAction.
type AttackAction struct {
	SourceInstanceID *string   `json:"sourceInstanceID,omitempty"`
	Type             string    `json:"type"`
	ValidTargets     *[]string `json:"validTargets,omitempty"`
}

// AttackEventData defines model for AttackEventData.
type AttackEventData struct {
	AttackerId string `json:"attackerId"`
	Cancelled  *bool  `json:"cancelled,omitempty"`
	Damage     int64  `json:"damage"`
	Destroyed  bool   `json:"destroyed"`
	SlaPenalty *int64 `json:"slaPenalty,omitempty"`
	TargetId   string `json:"targetId"`
}

// AvailableAction プレイヤーが現ターンに実行可能なアクション 1 件。`type` がアクション種別
// (play_card / attack など) を示し、その種別に必要なフィールドだけを持つ。
type AvailableAction struct {
	Type string `json:"type"`
}

// BattleDeckCard デッキスナップショット内の 1 枚のカード。
type BattleDeckCard struct {
	ArtNo  int64  `json:"art_no"`
	CardID string `json:"card_id"`
}

// BattleStartEventData defines model for BattleStartEventData.
type BattleStartEventData struct {
	MatchType     string `json:"match_type"`
	MyLevel       int64  `json:"my_level"`
	MyName        string `json:"my_name"`
	OpponentLevel int64  `json:"opponent_level"`
	OpponentName  string `json:"opponent_name"`
}

// ChoiceOption 選択肢 1 件。key は解決時に返す識別子 (branch キー / カード・インスタンス ID)。
type ChoiceOption struct {
	Key string `json:"key"`
}

// ClientGameState クライアントに返すゲーム状態スナップショット。
type ClientGameState struct {
	// ActivePlayer アクティブプレイヤー番号 (1 or 2)
	ActivePlayer int64 `json:"activePlayer"`

	// CurrentPhase 現在のフェーズ (`selecting` / `draw` / `yield` / `main` / `battle` / `end`)。
	// 定数マッピングは data/game_logic_constants.yaml 参照。
	CurrentPhase string `json:"currentPhase"`

	// CurrentTurn 現在のターン番号
	CurrentTurn int64 `json:"currentTurn"`

	// GameID ゲーム ID (ULID)
	GameID string `json:"gameID"`

	// IsMyTurn 自分のターンか
	IsMyTurn bool `json:"isMyTurn"`

	// MyView 自プレイヤー視点のスナップショット。
	MyView PlayerView `json:"myView"`

	// OppView 相手プレイヤー視点 (情報秘匿適用済み)。
	OppView OpponentView `json:"oppView"`

	// PendingEffectChoice pendingEffectChoice の client 公開ビュー。
	PendingEffectChoice *PendingEffectChoiceView `json:"pendingEffectChoice,omitempty"`

	// Player1Summary 対戦当時の player の name と level の snapshot (battle 開始時点の値、試合中不変)。
	// ClientGameState.player1Summary / player2Summary として client に pass-through される。
	// NPC のように level を持たない player では level は null となる。
	Player1Summary PlayerSummary `json:"player1Summary"`

	// Player2Summary 対戦当時の player の name と level の snapshot (battle 開始時点の値、試合中不変)。
	// ClientGameState.player1Summary / player2Summary として client に pass-through される。
	// NPC のように level を持たない player では level は null となる。
	Player2Summary PlayerSummary `json:"player2Summary"`

	// TurnStartedAt ターン開始日時
	TurnStartedAt time.Time `json:"turnStartedAt"`
}

// DeployedResource フィールドに展開済みのリソースカードインスタンス。
type DeployedResource struct {
	ArtNo     int64  `json:"artNo"`
	CardID    string `json:"cardID"`
	CurrentAV int64  `json:"currentAV"`

	// CurrentTP 現在のスループット (Compute のみ)
	CurrentTP *int64 `json:"currentTP,omitempty"`

	// CurrentYield 現在のイールド (Data のみ)
	CurrentYield *int64 `json:"currentYield,omitempty"`

	// Damage 受けたダメージ量
	Damage         int64 `json:"damage"`
	DeployOrder    int64 `json:"deployOrder"`
	DeployedOnTurn int64 `json:"deployedOnTurn"`

	// DeployingTurnsLeft デプロイ残りターン数 (0=アクティブ)
	DeployingTurnsLeft int64 `json:"deployingTurnsLeft"`
	EffectUsedThisGame bool  `json:"effectUsedThisGame"`
	EffectUsedThisTurn bool  `json:"effectUsedThisTurn"`
	ElasticBonus       int64 `json:"elasticBonus"`
	FaceUp             bool  `json:"faceUp"`
	HasAttacked        bool  `json:"hasAttacked"`

	// InstanceFamily インスタンスファミリー。game-design-constants の InstanceFamily に対応。
	InstanceFamily *string `json:"instanceFamily,omitempty"`
	InstanceID     string  `json:"instanceID"`
	LastAttackTurn int64   `json:"lastAttackTurn"`
	MaxAV          int64   `json:"maxAV"`
	MaxTP          *int64  `json:"maxTP,omitempty"`
	MaxYield       *int64  `json:"maxYield,omitempty"`

	// MonetizedAmount 収益化で配分された Insight 量
	MonetizedAmount int64 `json:"monetizedAmount"`

	// Rank ランク (S/M/L/XL)。game-design-constants の Rank に対応。
	Rank             *string           `json:"rank,omitempty"`
	TemporaryEffects []TemporaryEffect `json:"temporaryEffects"`
}

// DeployedSupport フィールドに展開済みのサポートカードインスタンス。
type DeployedSupport struct {
	ArtNo              int64  `json:"artNo"`
	CardID             string `json:"cardID"`
	DeployOrder        int64  `json:"deployOrder"`
	DeployingTurnsLeft int64  `json:"deployingTurnsLeft"`
	EffectUsedThisGame bool   `json:"effectUsedThisGame"`
	EffectUsedThisTurn bool   `json:"effectUsedThisTurn"`
	FaceUp             bool   `json:"faceUp"`
	InstanceID         string `json:"instanceID"`

	// TargetInstanceID Attachment 対象のインスタンス ID
	TargetInstanceID *string `json:"targetInstanceID,omitempty"`
}

// DevCard 開発用エンドポイント (/api/dev/cards) が返すカード一覧の 1 件。
type DevCard struct {
	CardID   string `json:"cardId"`
	CardName string `json:"cardName"`
	CardType string `json:"cardType"`
	Faction  string `json:"faction"`
}

// DiscardHandEventData defines model for DiscardHandEventData.
type DiscardHandEventData struct {
	DiscardedCount int32    `json:"discardedCount"`
	DiscardedIds   []string `json:"discardedIds"`
}

// Field 一方のプレイヤーのフィールド全体。
type Field struct {
	// Backend バックゾーン (3 スロット)、空き枠は null。
	Backend []DeployedResource `json:"backend"`

	// Frontend フロントゾーン (3 スロット)、空き枠は null。
	Frontend []DeployedResource `json:"frontend"`

	// Support サポートゾーン (3 スロット)、空き枠は null。
	Support []DeployedSupport `json:"support"`
}

// GameActionRequest POST /api/v1/games/{gameId}/actions のリクエスト body。
type GameActionRequest struct {
	ActionType string `json:"action_type"`

	// Data アクション固有の payload。サーバ側で action_type に応じて再パースされる。
	Data      map[string]interface{} `json:"data"`
	PlayerNum int64                  `json:"player_num"`
}

// GameCreatedResult NPC または PvP ゲーム作成時の battle server からの応答。
type GameCreatedResult struct {
	GameID string `json:"game_id"`
}

// GameOverEventData defines model for GameOverEventData.
type GameOverEventData struct {
	WinReason string `json:"winReason"`
	WinnerNum int64  `json:"winnerNum"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// HiddenDeployedSupport 表向き情報を隠蔽したサポートインスタンス。
type HiddenDeployedSupport struct {
	ArtNo int64 `json:"artNo"`

	// CardID カード ID (表向き、覗き見済み、またはデプロイ残りターン数が 1 以上の場合のみ含まれる)
	CardID *string `json:"cardID,omitempty"`

	// DeployingTurnsLeft デプロイ残りターン数 (0=アクティブ)。デプロイ中はカード名が公開されるため client の建設中表示に使う
	DeployingTurnsLeft int64  `json:"deployingTurnsLeft"`
	FaceDown           bool   `json:"faceDown"`
	InstanceID         string `json:"instanceID"`

	// Peeked 覗き見されたか
	Peeked bool `json:"peeked"`
}

// MonetizeAction defines model for MonetizeAction.
type MonetizeAction struct {
	RemainingCapacity *int64  `json:"remainingCapacity,omitempty"`
	SourceInstanceID  *string `json:"sourceInstanceID,omitempty"`
	Type              string  `json:"type"`
}

// MonetizeEventData defines model for MonetizeEventData.
type MonetizeEventData struct {
	TotalAmount int64 `json:"totalAmount"`
}

// NpcBattleRequest POST /api/v1/games/npc のリクエスト body。
type NpcBattleRequest struct {
	DeckCards []BattleDeckCard `json:"deck_cards"`
	NpcModel  string           `json:"npc_model"`

	// Player1Summary CreatePvP / CreateNpc API で battle に渡す player の name と level の snapshot。
	// battle は upstream (account 等) に依存せず、渡された値を player_summary テーブルに
	// 永続化する。NPC のように level を持たない player では level は null となる。
	Player1Summary PlayerSummaryRequest `json:"player1_summary"`

	// Player2Summary CreatePvP / CreateNpc API で battle に渡す player の name と level の snapshot。
	// battle は upstream (account 等) に依存せず、渡された値を player_summary テーブルに
	// 永続化する。NPC のように level を持たない player では level は null となる。
	Player2Summary PlayerSummaryRequest `json:"player2_summary"`

	// RoutineId デッキに設定されたルーチン施策の ID。
	RoutineId string `json:"routine_id"`

	// SpecialId デッキに設定されたスペシャル施策の ID。
	SpecialId string `json:"special_id"`
}

// NpcModelEntry defines model for NpcModelEntry.
type NpcModelEntry struct {
	Difficulty  string `json:"difficulty"`
	DisplayName string `json:"display_name"`
	Faction     string `json:"faction"`
	Model       string `json:"model"`
}

// NpcModelsResponse defines model for NpcModelsResponse.
type NpcModelsResponse struct {
	Models []NpcModelEntry `json:"models"`
}

// OpponentField 相手のフィールド (サポートは非公開カード隠蔽)。
type OpponentField struct {
	Backend  []DeployedResource      `json:"backend"`
	Frontend []DeployedResource      `json:"frontend"`
	Support  []HiddenDeployedSupport `json:"support"`
}

// OpponentView 相手プレイヤー視点 (情報秘匿適用済み)。
type OpponentView struct {
	Budget int64 `json:"budget"`

	// Field 相手のフィールド (サポートは非公開カード隠蔽)。
	Field OpponentField `json:"field"`

	// HandCount 手札枚数 (内容は非公開)
	HandCount   int32            `json:"handCount"`
	InsightPool int64            `json:"insightPool"`
	PlayerNum   int64            `json:"playerNum"`
	RepoCount   int32            `json:"repoCount"`
	TimeBank    int64            `json:"timeBank"`
	Trash       []UndeployedCard `json:"trash"`
	TrashCount  int32            `json:"trashCount"`
}

// PendingEffectChoiceView pendingEffectChoice の client 公開ビュー。
type PendingEffectChoiceView struct {
	// ChoiceKind 選択対象の種別 (hand_card / field_target / deck_top)。選択肢の提示は resolve_pending_choice アクションの choiceOptions が担う。
	ChoiceKind string `json:"choiceKind"`

	// ChooserPlayerNum 選択を行うプレイヤー番号
	ChooserPlayerNum int64 `json:"chooserPlayerNum"`

	// EffectCardId 発動中の効果を持つカードの ID
	EffectCardId string `json:"effectCardId"`

	// EffectInstanceId 発動中の効果を持つカードのインスタンス ID
	EffectInstanceId string `json:"effectInstanceId"`
}

// PendingSlotSelectView 効果からのリソースデプロイを待っているスロット選択の client 公開ビュー。
type PendingSlotSelectView struct {
	// Resource フィールドに展開済みのリソースカードインスタンス。
	Resource DeployedResource `json:"resource"`

	// ValidZones 配置可能なゾーンとスロット ("frontend_0" 等)。
	ValidZones []string `json:"validZones"`
}

// PhaseChangeEventData defines model for PhaseChangeEventData.
type PhaseChangeEventData struct {
	CurrentPhase  string `json:"currentPhase"`
	PreviousPhase string `json:"previousPhase"`
}

// PhaseEndEventData defines model for PhaseEndEventData.
type PhaseEndEventData struct {
	NeedsDiscard bool   `json:"needsDiscard"`
	Phase        string `json:"phase"`
}

// PlayCardAction defines model for PlayCardAction.
type PlayCardAction struct {
	CardID           *string   `json:"cardID,omitempty"`
	EffectTargetType *string   `json:"effectTargetType,omitempty"`
	HandInstanceID   *string   `json:"handInstanceID,omitempty"`
	Type             string    `json:"type"`
	ValidTargets     *[]string `json:"validTargets,omitempty"`
	ValidZones       *[]string `json:"validZones,omitempty"`
}

// PlayCardEventData defines model for PlayCardEventData.
type PlayCardEventData struct {
	Cancelled *bool  `json:"cancelled,omitempty"`
	CardId    string `json:"cardId"`
	Index     int32  `json:"index"`
	Zone      string `json:"zone"`
}

// PlayerSummary 対戦当時の player の name と level の snapshot (battle 開始時点の値、試合中不変)。
// ClientGameState.player1Summary / player2Summary として client に pass-through される。
// NPC のように level を持たない player では level は null となる。
type PlayerSummary struct {
	// Level level snapshot (NPC など level を持たない player では null)
	Level *int64 `json:"level,omitempty"`

	// Name 表示名 snapshot
	Name string `json:"name"`
}

// PlayerSummaryRequest CreatePvP / CreateNpc API で battle に渡す player の name と level の snapshot。
// battle は upstream (account 等) に依存せず、渡された値を player_summary テーブルに
// 永続化する。NPC のように level を持たない player では level は null となる。
type PlayerSummaryRequest struct {
	// Level level snapshot (NPC など level を持たない player では null)
	Level *int64 `json:"level,omitempty"`

	// Name 表示名 snapshot
	Name string `json:"name"`
}

// PlayerView 自プレイヤー視点のスナップショット。
type PlayerView struct {
	// AvailableActions 実行可能アクション一覧 (アクティブプレイヤーのみ)。
	AvailableActions *[]AvailableAction `json:"availableActions,omitempty"`
	Budget           int64              `json:"budget"`

	// Field 一方のプレイヤーのフィールド全体。
	Field       Field            `json:"field"`
	Hand        []UndeployedCard `json:"hand"`
	InsightPool int64            `json:"insightPool"`

	// PendingSlotSelect 効果からのリソースデプロイを待っているスロット選択の client 公開ビュー。
	PendingSlotSelect *PendingSlotSelectView `json:"pendingSlotSelect,omitempty"`
	PlayerNum         int64                  `json:"playerNum"`

	// RepoCount リポジトリ残り枚数
	RepoCount int32 `json:"repoCount"`

	// TimeBank タイムバンク (秒)
	TimeBank   int64            `json:"timeBank"`
	Trash      []UndeployedCard `json:"trash"`
	TrashCount int32            `json:"trashCount"`
}

// PvpBattleRequest POST /api/v1/games/pvp のリクエスト body。
type PvpBattleRequest struct {
	Deck1Cards []BattleDeckCard `json:"deck1_cards"`

	// Deck1RoutineId デッキ 1 に設定されたルーチン施策の ID。
	Deck1RoutineId string `json:"deck1_routine_id"`

	// Deck1SpecialId デッキ 1 に設定されたスペシャル施策の ID。
	Deck1SpecialId string           `json:"deck1_special_id"`
	Deck2Cards     []BattleDeckCard `json:"deck2_cards"`

	// Deck2RoutineId デッキ 2 に設定されたルーチン施策の ID。
	Deck2RoutineId string `json:"deck2_routine_id"`

	// Deck2SpecialId デッキ 2 に設定されたスペシャル施策の ID。
	Deck2SpecialId string `json:"deck2_special_id"`

	// Player1Summary CreatePvP / CreateNpc API で battle に渡す player の name と level の snapshot。
	// battle は upstream (account 等) に依存せず、渡された値を player_summary テーブルに
	// 永続化する。NPC のように level を持たない player では level は null となる。
	Player1Summary PlayerSummaryRequest `json:"player1_summary"`

	// Player2Summary CreatePvP / CreateNpc API で battle に渡す player の name と level の snapshot。
	// battle は upstream (account 等) に依存せず、渡された値を player_summary テーブルに
	// 永続化する。NPC のように level を持たない player では level は null となる。
	Player2Summary PlayerSummaryRequest `json:"player2_summary"`
}

// ReactiveRevealedEventData defines model for ReactiveRevealedEventData.
type ReactiveRevealedEventData struct {
	CardId     string `json:"cardId"`
	InstanceId string `json:"instanceId"`
}

// ResolvePendingChoiceAction defines model for ResolvePendingChoiceAction.
type ResolvePendingChoiceAction struct {
	// ChoiceKind 選択対象の種別 (hand_card / field_target / deck_top)。
	ChoiceKind    *string         `json:"choiceKind,omitempty"`
	ChoiceOptions *[]ChoiceOption `json:"choiceOptions,omitempty"`

	// EffectCardId 発動中の効果を持つカードの ID
	EffectCardId *string `json:"effectCardId,omitempty"`

	// RevealedDeckTop deck_top 選択で選択するプレイヤーにだけ開示するデッキ上端カード。各 instanceID が choiceOptions[].key に対応する。
	RevealedDeckTop *[]UndeployedCard `json:"revealedDeckTop,omitempty"`
	Type            string            `json:"type"`
}

// ScaleUpAction defines model for ScaleUpAction.
type ScaleUpAction struct {
	InstanceFamily   *string `json:"instanceFamily,omitempty"`
	NeedsFamily      *bool   `json:"needsFamily,omitempty"`
	SourceInstanceID *string `json:"sourceInstanceID,omitempty"`
	TargetRank       *string `json:"targetRank,omitempty"`
	Type             string  `json:"type"`
}

// ScaleUpEventData defines model for ScaleUpEventData.
type ScaleUpEventData struct {
	InstanceFamily *string `json:"instanceFamily,omitempty"`
	InstanceId     string  `json:"instanceId"`
	TargetRank     string  `json:"targetRank"`
}

// SelectSlotEventData defines model for SelectSlotEventData.
type SelectSlotEventData struct {
	CardId     string `json:"cardId"`
	Index      int32  `json:"index"`
	InstanceId string `json:"instanceId"`
	Zone       string `json:"zone"`
}

// TemporaryEffect カードに付与されている一時効果。
type TemporaryEffect struct {
	// Duration 持続期間 (`until_end_of_turn` / `permanent` 等)。
	Duration   string `json:"duration"`
	EffectType string `json:"effectType"`

	// Mode バフモード (空文字=flat / `percent`=割合)
	Mode string `json:"mode"`

	// SourceID 効果の発生源インスタンス ID
	SourceID string `json:"sourceID"`
	Value    int64  `json:"value"`
}

// TurnControlsMessage 現在のターン操作可否を表すメッセージ。
type TurnControlsMessage struct {
	// CanEndPhase 現在のフェーズを終了できるか (main / battle フェーズで `true`)
	CanEndPhase bool `json:"canEndPhase"`

	// DiscardRequired 手札破棄が必要な枚数 (end フェーズで手札 > 6 枚の場合のみ > 0)
	DiscardRequired int32 `json:"discardRequired"`
}

// TurnEndEventData defines model for TurnEndEventData.
type TurnEndEventData struct {
	ActivePlayer int64  `json:"activePlayer"`
	CurrentPhase string `json:"currentPhase"`
	NextTurn     int64  `json:"nextTurn"`
	Phase        string `json:"phase"`
}

// TurnStartEventData defines model for TurnStartEventData.
type TurnStartEventData struct {
	IsMyTurn bool  `json:"is_my_turn"`
	Turn     int64 `json:"turn"`
}

// UndeployedCard 手札・トラッシュ等にあるカード。
type UndeployedCard struct {
	ArtNo      int64  `json:"artNo"`
	CardID     string `json:"cardID"`
	InstanceID string `json:"instanceID"`
}

// UseIgnitionAction defines model for UseIgnitionAction.
type UseIgnitionAction struct {
	CardID           *string   `json:"cardID,omitempty"`
	EffectTargetType *string   `json:"effectTargetType,omitempty"`
	RequiredCount    *int32    `json:"requiredCount,omitempty"`
	SourceInstanceID *string   `json:"sourceInstanceID,omitempty"`
	Type             string    `json:"type"`
	ValidTargets     *[]string `json:"validTargets,omitempty"`
}

// UseIgnitionEventData defines model for UseIgnitionEventData.
type UseIgnitionEventData struct {
	CardId   string  `json:"cardId"`
	SourceId string  `json:"sourceId"`
	TargetId *string `json:"targetId,omitempty"`
}

// UseInitiativeAction defines model for UseInitiativeAction.
type UseInitiativeAction struct {
	CardID           *string `json:"cardID,omitempty"`
	Cost             *int64  `json:"cost,omitempty"`
	EffectTargetType *string `json:"effectTargetType,omitempty"`

	// Kind 施策の区分 (routine / special)。
	Kind         *string   `json:"kind,omitempty"`
	Type         string    `json:"type"`
	ValidTargets *[]string `json:"validTargets,omitempty"`
}

// UseInitiativeEventData defines model for UseInitiativeEventData.
type UseInitiativeEventData struct {
	InitiativeId   string `json:"initiativeId"`
	InitiativeName string `json:"initiativeName"`
	InsightCost    int64  `json:"insightCost"`
	Kind           string `json:"kind"`
	ProductId      string `json:"productId"`
}

// GameIdPath defines model for GameIdPath.
type GameIdPath = string

// PlayerNumPath defines model for PlayerNumPath.
type PlayerNumPath = int32

// CreateNpcGameJSONRequestBody defines body for CreateNpcGame for application/json ContentType.
type CreateNpcGameJSONRequestBody = NpcBattleRequest

// CreatePvpGameJSONRequestBody defines body for CreatePvpGame for application/json ContentType.
type CreatePvpGameJSONRequestBody = PvpBattleRequest

// ProcessGameActionJSONRequestBody defines body for ProcessGameAction for application/json ContentType.
type ProcessGameActionJSONRequestBody = GameActionRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListDevCards request
	ListDevCards(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateNpcGameWithBody request with any body
	CreateNpcGameWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateNpcGame(ctx context.Context, body CreateNpcGameJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePvpGameWithBody request with any body
	CreatePvpGameWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreatePvpGame(ctx context.Context, body CreatePvpGameJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ProcessGameActionWithBody request with any body
	ProcessGameActionWithBody(ctx context.Context, gameId GameIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ProcessGameAction(ctx context.Context, gameId GameIdPath, body ProcessGameActionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AdvanceNpcTurn request
	AdvanceNpcTurn(ctx context.Context, gameId GameIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTurnControlsForPlayer request
	GetTurnControlsForPlayer(ctx context.Context, gameId GameIdPath, playerNum PlayerNumPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGameLogJson request
	GetGameLogJson(ctx context.Context, gameId GameIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGameLogText request
	GetGameLogText(ctx context.Context, gameId GameIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGameStateForPlayer request
	GetGameStateForPlayer(ctx context.Context, gameId GameIdPath, playerNum PlayerNumPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListNpcModels request
	ListNpcModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListDevCards(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDevCardsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateNpcGameWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateNpcGameRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateNpcGame(ctx context.Context, body CreateNpcGameJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateNpcGameRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePvpGameWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePvpGameRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePvpGame(ctx context.Context, body CreatePvpGameJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePvpGameRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProcessGameActionWithBody(ctx context.Context, gameId GameIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProcessGameActionRequestWithBody(c.Server, gameId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProcessGameAction(ctx context.Context, gameId GameIdPath, body ProcessGameActionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProcessGameActionRequest(c.Server, gameId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AdvanceNpcTurn(ctx context.Context, gameId GameIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAdvanceNpcTurnRequest(c.Server, gameId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTurnControlsForPlayer(ctx context.Context, gameId GameIdPath, playerNum PlayerNumPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTurnControlsForPlayerRequest(c.Server, gameId, playerNum)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGameLogJson(ctx context.Context, gameId GameIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGameLogJsonRequest(c.Server, gameId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGameLogText(ctx context.Context, gameId GameIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGameLogTextRequest(c.Server, gameId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGameStateForPlayer(ctx context.Context, gameId GameIdPath, playerNum PlayerNumPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGameStateForPlayerRequest(c.Server, gameId, playerNum)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListNpcModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListNpcModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListDevCardsRequest generates requests for ListDevCards
func NewListDevCardsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/dev/cards")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateNpcGameRequest calls the generic CreateNpcGame builder with application/json body
func NewCreateNpcGameRequest(server string, body CreateNpcGameJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateNpcGameRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateNpcGameRequestWithBody generates requests for CreateNpcGame with any type of body
func NewCreateNpcGameRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/games/npc")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreatePvpGameRequest calls the generic CreatePvpGame builder with application/json body
func NewCreatePvpGameRequest(server string, body CreatePvpGameJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePvpGameRequestWithBody(server, "application/json", bodyReader)
}

// NewCreatePvpGameRequestWithBody generates requests for CreatePvpGame with any type of body
func NewCreatePvpGameRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/games/pvp")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewProcessGameActionRequest calls the generic ProcessGameAction builder with application/json body
func NewProcessGameActionRequest(server string, gameId GameIdPath, body ProcessGameActionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewProcessGameActionRequestWithBody(server, gameId, "application/json", bodyReader)
}

// NewProcessGameActionRequestWithBody generates requests for ProcessGameAction with any type of body
func NewProcessGameActionRequestWithBody(server string, gameId GameIdPath, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "gameId", gameId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/games/%s/actions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAdvanceNpcTurnRequest generates requests for AdvanceNpcTurn
func NewAdvanceNpcTurnRequest(server string, gameId GameIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "gameId", gameId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/games/%s/advance-npc", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTurnControlsForPlayerRequest generates requests for GetTurnControlsForPlayer
func NewGetTurnControlsForPlayerRequest(server string, gameId GameIdPath, playerNum PlayerNumPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "gameId", gameId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "playerNum", playerNum, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/games/%s/controls/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetGameLogJsonRequest generates requests for GetGameLogJson
func NewGetGameLogJsonRequest(server string, gameId GameIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "gameId", gameId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/games/%s/log", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetGameLogTextRequest generates requests for GetGameLogText
func NewGetGameLogTextRequest(server string, gameId GameIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "gameId", gameId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/games/%s/log/text", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetGameStateForPlayerRequest generates requests for GetGameStateForPlayer
func NewGetGameStateForPlayerRequest(server string, gameId GameIdPath, playerNum PlayerNumPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "gameId", gameId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "playerNum", playerNum, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/games/%s/state/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListNpcModelsRequest generates requests for ListNpcModels
func NewListNpcModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/npc/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListDevCardsWithResponse request
	ListDevCardsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDevCardsResponse, error)

	// CreateNpcGameWithBodyWithResponse request with any body
	CreateNpcGameWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateNpcGameResponse, error)

	CreateNpcGameWithResponse(ctx context.Context, body CreateNpcGameJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateNpcGameResponse, error)

	// CreatePvpGameWithBodyWithResponse request with any body
	CreatePvpGameWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePvpGameResponse, error)

	CreatePvpGameWithResponse(ctx context.Context, body CreatePvpGameJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePvpGameResponse, error)

	// ProcessGameActionWithBodyWithResponse request with any body
	ProcessGameActionWithBodyWithResponse(ctx context.Context, gameId GameIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ProcessGameActionResponse, error)

	ProcessGameActionWithResponse(ctx context.Context, gameId GameIdPath, body ProcessGameActionJSONRequestBody, reqEditors ...RequestEditorFn) (*ProcessGameActionResponse, error)

	// AdvanceNpcTurnWithResponse request
	AdvanceNpcTurnWithResponse(ctx context.Context, gameId GameIdPath, reqEditors ...RequestEditorFn) (*AdvanceNpcTurnResponse, error)

	// GetTurnControlsForPlayerWithResponse request
	GetTurnControlsForPlayerWithResponse(ctx context.Context, gameId GameIdPath, playerNum PlayerNumPath, reqEditors ...RequestEditorFn) (*GetTurnControlsForPlayerResponse, error)

	// GetGameLogJsonWithResponse request
	GetGameLogJsonWithResponse(ctx context.Context, gameId GameIdPath, reqEditors ...RequestEditorFn) (*GetGameLogJsonResponse, error)

	// GetGameLogTextWithResponse request
	GetGameLogTextWithResponse(ctx context.Context, gameId GameIdPath, reqEditors ...RequestEditorFn) (*GetGameLogTextResponse, error)

	// GetGameStateForPlayerWithResponse request
	GetGameStateForPlayerWithResponse(ctx context.Context, gameId GameIdPath, playerNum PlayerNumPath, reqEditors ...RequestEditorFn) (*GetGameStateForPlayerResponse, error)

	// ListNpcModelsWithResponse request
	ListNpcModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListNpcModelsResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)
}

type ListDevCardsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]DevCard
}

// Status returns HTTPResponse.Status
func (r ListDevCardsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDevCardsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDevCardsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateNpcGameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GameCreatedResult
}

// Status returns HTTPResponse.Status
func (r CreateNpcGameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateNpcGameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateNpcGameResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreatePvpGameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GameCreatedResult
}

// Status returns HTTPResponse.Status
func (r CreatePvpGameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePvpGameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreatePvpGameResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ProcessGameActionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ActionResult
}

// Status returns HTTPResponse.Status
func (r ProcessGameActionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProcessGameActionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ProcessGameActionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AdvanceNpcTurnResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ActionResult
}

// Status returns HTTPResponse.Status
func (r AdvanceNpcTurnResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AdvanceNpcTurnResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AdvanceNpcTurnResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetTurnControlsForPlayerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TurnControlsMessage
}

// Status returns HTTPResponse.Status
func (r GetTurnControlsForPlayerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTurnControlsForPlayerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTurnControlsForPlayerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetGameLogJsonResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
}

// Status returns HTTPResponse.Status
func (r GetGameLogJsonResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGameLogJsonResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetGameLogJsonResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetGameLogTextResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetGameLogTextResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGameLogTextResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetGameLogTextResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetGameStateForPlayerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ClientGameState
}

// Status returns HTTPResponse.Status
func (r GetGameStateForPlayerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGameStateForPlayerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetGameStateForPlayerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListNpcModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NpcModelsResponse
}

// Status returns HTTPResponse.Status
func (r ListNpcModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListNpcModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListNpcModelsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListDevCardsWithResponse request returning *ListDevCardsResponse
func (c *ClientWithResponses) ListDevCardsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDevCardsResponse, error) {
	rsp, err := c.ListDevCards(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDevCardsResponse(rsp)
}

// CreateNpcGameWithBodyWithResponse request with arbitrary body returning *CreateNpcGameResponse
func (c *ClientWithResponses) CreateNpcGameWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateNpcGameResponse, error) {
	rsp, err := c.CreateNpcGameWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNpcGameResponse(rsp)
}

func (c *ClientWithResponses) CreateNpcGameWithResponse(ctx context.Context, body CreateNpcGameJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateNpcGameResponse, error) {
	rsp, err := c.CreateNpcGame(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNpcGameResponse(rsp)
}

// CreatePvpGameWithBodyWithResponse request with arbitrary body returning *CreatePvpGameResponse
func (c *ClientWithResponses) CreatePvpGameWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePvpGameResponse, error) {
	rsp, err := c.CreatePvpGameWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePvpGameResponse(rsp)
}

func (c *ClientWithResponses) CreatePvpGameWithResponse(ctx context.Context, body CreatePvpGameJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePvpGameResponse, error) {
	rsp, err := c.CreatePvpGame(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePvpGameResponse(rsp)
}

// ProcessGameActionWithBodyWithResponse request with arbitrary body returning *ProcessGameActionResponse
func (c *ClientWithResponses) ProcessGameActionWithBodyWithResponse(ctx context.Context, gameId GameIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ProcessGameActionResponse, error) {
	rsp, err := c.ProcessGameActionWithBody(ctx, gameId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProcessGameActionResponse(rsp)
}

func (c *ClientWithResponses) ProcessGameActionWithResponse(ctx context.Context, gameId GameIdPath, body ProcessGameActionJSONRequestBody, reqEditors ...RequestEditorFn) (*ProcessGameActionResponse, error) {
	rsp, err := c.ProcessGameAction(ctx, gameId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProcessGameActionResponse(rsp)
}

// AdvanceNpcTurnWithResponse request returning *AdvanceNpcTurnResponse
func (c *ClientWithResponses) AdvanceNpcTurnWithResponse(ctx context.Context, gameId GameIdPath, reqEditors ...RequestEditorFn) (*AdvanceNpcTurnResponse, error) {
	rsp, err := c.AdvanceNpcTurn(ctx, gameId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAdvanceNpcTurnResponse(rsp)
}

// GetTurnControlsForPlayerWithResponse request returning *GetTurnControlsForPlayerResponse
func (c *ClientWithResponses) GetTurnControlsForPlayerWithResponse(ctx context.Context, gameId GameIdPath, playerNum PlayerNumPath, reqEditors ...RequestEditorFn) (*GetTurnControlsForPlayerResponse, error) {
	rsp, err := c.GetTurnControlsForPlayer(ctx, gameId, playerNum, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTurnControlsForPlayerResponse(rsp)
}

// GetGameLogJsonWithResponse request returning *GetGameLogJsonResponse
func (c *ClientWithResponses) GetGameLogJsonWithResponse(ctx context.Context, gameId GameIdPath, reqEditors ...RequestEditorFn) (*GetGameLogJsonResponse, error) {
	rsp, err := c.GetGameLogJson(ctx, gameId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGameLogJsonResponse(rsp)
}

// GetGameLogTextWithResponse request returning *GetGameLogTextResponse
func (c *ClientWithResponses) GetGameLogTextWithResponse(ctx context.Context, gameId GameIdPath, reqEditors ...RequestEditorFn) (*GetGameLogTextResponse, error) {
	rsp, err := c.GetGameLogText(ctx, gameId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGameLogTextResponse(rsp)
}

// GetGameStateForPlayerWithResponse request returning *GetGameStateForPlayerResponse
func (c *ClientWithResponses) GetGameStateForPlayerWithResponse(ctx context.Context, gameId GameIdPath, playerNum PlayerNumPath, reqEditors ...RequestEditorFn) (*GetGameStateForPlayerResponse, error) {
	rsp, err := c.GetGameStateForPlayer(ctx, gameId, playerNum, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGameStateForPlayerResponse(rsp)
}

// ListNpcModelsWithResponse request returning *ListNpcModelsResponse
func (c *ClientWithResponses) ListNpcModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListNpcModelsResponse, error) {
	rsp, err := c.ListNpcModels(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListNpcModelsResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ParseListDevCardsResponse parses an HTTP response from a ListDevCardsWithResponse call
func ParseListDevCardsResponse(rsp *http.Response) (*ListDevCardsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDevCardsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []DevCard
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateNpcGameResponse parses an HTTP response from a CreateNpcGameWithResponse call
func ParseCreateNpcGameResponse(rsp *http.Response) (*CreateNpcGameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateNpcGameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GameCreatedResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreatePvpGameResponse parses an HTTP response from a CreatePvpGameWithResponse call
func ParseCreatePvpGameResponse(rsp *http.Response) (*CreatePvpGameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePvpGameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GameCreatedResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseProcessGameActionResponse parses an HTTP response from a ProcessGameActionWithResponse call
func ParseProcessGameActionResponse(rsp *http.Response) (*ProcessGameActionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProcessGameActionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ActionResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAdvanceNpcTurnResponse parses an HTTP response from a AdvanceNpcTurnWithResponse call
func ParseAdvanceNpcTurnResponse(rsp *http.Response) (*AdvanceNpcTurnResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AdvanceNpcTurnResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ActionResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetTurnControlsForPlayerResponse parses an HTTP response from a GetTurnControlsForPlayerWithResponse call
func ParseGetTurnControlsForPlayerResponse(rsp *http.Response) (*GetTurnControlsForPlayerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTurnControlsForPlayerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TurnControlsMessage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetGameLogJsonResponse parses an HTTP response from a GetGameLogJsonWithResponse call
func ParseGetGameLogJsonResponse(rsp *http.Response) (*GetGameLogJsonResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGameLogJsonResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetGameLogTextResponse parses an HTTP response from a GetGameLogTextWithResponse call
func ParseGetGameLogTextResponse(rsp *http.Response) (*GetGameLogTextResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGameLogTextResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetGameStateForPlayerResponse parses an HTTP response from a GetGameStateForPlayerWithResponse call
func ParseGetGameStateForPlayerResponse(rsp *http.Response) (*GetGameStateForPlayerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGameStateForPlayerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ClientGameState
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListNpcModelsResponse parses an HTTP response from a ListNpcModelsWithResponse call
func ParseListNpcModelsResponse(rsp *http.Response) (*ListNpcModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListNpcModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NpcModelsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
