// Package apibattle provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apibattle

import (
	"time"
)

// ActionEvent アクション処理後に battle server が emit する 1 件のゲームイベント。
type ActionEvent struct {
	// EventData イベント種別固有の payload。Go / C# では opaque な map / JsonElement として扱い、
	// event_type ごとに用意された EventData schema で再 unmarshal する。
	EventData map[string]interface{} `json:"event_data"`
	EventType string                 `json:"event_type"`

	// PlayerNum アクション元のスロット番号 (1 or 2)。system event (turn_start 等) では null。
	PlayerNum *int64 `json:"player_num"`
	Sequence  int64  `json:"sequence"`

	// State イベント直後のゲーム状態スナップショット。`event_data` 同様 opaque。
	State map[string]interface{} `json:"state"`
}

// ActionResult ゲームアクション処理後に返される結果。
type ActionResult struct {
	// Events このアクションで発生したイベント列。
	Events []ActionEvent `json:"events"`

	// GameOver ゲーム終了フラグ
	GameOver bool `json:"game_over"`

	// NpcPending true の場合、Gateway は AdvanceNpcTurn を呼んで次の NPC アクションを取得する必要がある。
	NpcPending bool `json:"npc_pending"`

	// WinReason 終了理由 (WinReasons enum の文字列、未終了時は空文字)
	WinReason string `json:"win_reason"`

	// WinningPlayerNum 勝者プレイヤー番号 (1 or 2、未終了時は 0)
	WinningPlayerNum int64 `json:"winning_player_num"`
}

// AttachCardEventData defines model for AttachCardEventData.
type AttachCardEventData struct {
	CardId   string `json:"cardId"`
	TargetId string `json:"targetId"`
}

// AttackEventData defines model for AttackEventData.
type AttackEventData struct {
	AttackerId string `json:"attackerId"`
	Cancelled  *bool  `json:"cancelled,omitempty"`
	Damage     int64  `json:"damage"`
	Destroyed  bool   `json:"destroyed"`
	SlaPenalty *int64 `json:"slaPenalty,omitempty"`
	TargetId   string `json:"targetId"`
}

// AvailableAction プレイヤーが現ターンに実行可能なアクション。`type` discriminator で variant を判別する。
// 各 variant 固有のフィールドは optional。flat shape を維持しているのは既存 C# server / TS client
// の実装を温存するため (oneOf による正規化は将来検討)。
type AvailableAction struct {
	CardID            *string   `json:"cardID,omitempty"`
	ChoiceOptions     *[]string `json:"choiceOptions,omitempty"`
	Cost              *int32    `json:"cost,omitempty"`
	EffectTargetType  *string   `json:"effectTargetType,omitempty"`
	HandInstanceID    *string   `json:"handInstanceID,omitempty"`
	InstanceFamily    *string   `json:"instanceFamily,omitempty"`
	NeedsFamily       *bool     `json:"needsFamily,omitempty"`
	RemainingCapacity *int64    `json:"remainingCapacity,omitempty"`
	RequiredCount     *int32    `json:"requiredCount,omitempty"`
	SourceInstanceID  *string   `json:"sourceInstanceID,omitempty"`
	TargetRank        *string   `json:"targetRank,omitempty"`

	// Type variant 種別。`play_card` / `attack` / `scale_up` / `monetize` / `use_effect` のいずれか。
	Type         string    `json:"type"`
	ValidTargets *[]string `json:"validTargets,omitempty"`
	ValidZones   *[]string `json:"validZones,omitempty"`
}

// BattleDeckCard デッキスナップショット内の 1 枚のカード。
type BattleDeckCard struct {
	ArtNo  int64  `json:"art_no"`
	CardID string `json:"card_id"`
}

// BattleStartEventData defines model for BattleStartEventData.
type BattleStartEventData struct {
	MatchType     string `json:"match_type"`
	MyLevel       int64  `json:"my_level"`
	MyName        string `json:"my_name"`
	OpponentLevel int64  `json:"opponent_level"`
	OpponentName  string `json:"opponent_name"`
}

// ClientGameState クライアントに返すゲーム状態スナップショット。
type ClientGameState struct {
	// ActivePlayer アクティブプレイヤー番号 (1 or 2)
	ActivePlayer int64 `json:"activePlayer"`

	// CurrentPhase 現在のフェーズ (`selecting` / `draw` / `yield` / `main` / `battle` / `end`)。
	// game-logic-constants の GamePhase に対応するが OpenAPI 上は string で扱う
	// (定数 SSoT は data/game_logic_constants.yaml で別途維持)。
	CurrentPhase string `json:"currentPhase"`

	// CurrentTurn 現在のターン番号
	CurrentTurn int64 `json:"currentTurn"`

	// GameID ゲーム ID (ULID)
	GameID string `json:"gameID"`

	// IsMyTurn 自分のターンか
	IsMyTurn bool `json:"isMyTurn"`

	// MyView 自プレイヤー視点のスナップショット。
	MyView PlayerView `json:"myView"`

	// OppView 相手プレイヤー視点 (情報秘匿適用済み)。
	OppView OpponentView `json:"oppView"`

	// TurnStartedAt ターン開始日時
	TurnStartedAt time.Time `json:"turnStartedAt"`
}

// DeployedResource フィールドに展開済みのリソースカードインスタンス。
type DeployedResource struct {
	ArtNo     int64  `json:"artNo"`
	CardID    string `json:"cardID"`
	CurrentAV int64  `json:"currentAV"`

	// CurrentTP 現在のスループット (Compute のみ)
	CurrentTP *int64 `json:"currentTP,omitempty"`

	// CurrentYield 現在のイールド (Data のみ)
	CurrentYield *int64 `json:"currentYield,omitempty"`

	// Damage 受けたダメージ量
	Damage         int64 `json:"damage"`
	DeployOrder    int64 `json:"deployOrder"`
	DeployedOnTurn int64 `json:"deployedOnTurn"`

	// DeployingTurnsLeft デプロイ残りターン数 (0=アクティブ)
	DeployingTurnsLeft int64 `json:"deployingTurnsLeft"`
	EffectUsedThisGame bool  `json:"effectUsedThisGame"`
	EffectUsedThisTurn bool  `json:"effectUsedThisTurn"`
	ElasticBonus       int64 `json:"elasticBonus"`
	FaceUp             bool  `json:"faceUp"`
	HasAttacked        bool  `json:"hasAttacked"`

	// InstanceFamily インスタンスファミリー。game-design-constants の InstanceFamily に対応。
	InstanceFamily *string `json:"instanceFamily,omitempty"`
	InstanceID     string  `json:"instanceID"`
	LastAttackTurn int64   `json:"lastAttackTurn"`
	MaxAV          int64   `json:"maxAV"`
	MaxTP          *int64  `json:"maxTP,omitempty"`
	MaxYield       *int64  `json:"maxYield,omitempty"`

	// MonetizedAmount 収益化で配分された Insight 量
	MonetizedAmount int64 `json:"monetizedAmount"`

	// Rank ランク (S/M/L/XL)。game-design-constants の Rank に対応。
	Rank             *string           `json:"rank,omitempty"`
	TemporaryEffects []TemporaryEffect `json:"temporaryEffects"`
}

// DeployedSupport フィールドに展開済みのサポートカードインスタンス。
type DeployedSupport struct {
	ArtNo              int64  `json:"artNo"`
	CardID             string `json:"cardID"`
	DeployOrder        int64  `json:"deployOrder"`
	DeployingTurnsLeft int64  `json:"deployingTurnsLeft"`
	EffectUsedThisGame bool   `json:"effectUsedThisGame"`
	EffectUsedThisTurn bool   `json:"effectUsedThisTurn"`
	FaceUp             bool   `json:"faceUp"`
	InstanceID         string `json:"instanceID"`

	// TargetInstanceID Attachment 対象のインスタンス ID
	TargetInstanceID *string `json:"targetInstanceID,omitempty"`
}

// DevCard 開発用エンドポイント (/api/dev/cards) が返すカード一覧の 1 件。
type DevCard struct {
	CardID   string `json:"cardId"`
	CardName string `json:"cardName"`
	CardType string `json:"cardType"`
	Faction  string `json:"faction"`
}

// DiscardHandEventData defines model for DiscardHandEventData.
type DiscardHandEventData struct {
	DiscardedCount int32    `json:"discardedCount"`
	DiscardedIds   []string `json:"discardedIds"`
}

// Field 一方のプレイヤーのフィールド全体。
type Field struct {
	// Backend バックゾーン (3 スロット)、空き枠は null。
	Backend []DeployedResource `json:"backend"`

	// Frontend フロントゾーン (3 スロット)、空き枠は null。
	Frontend []DeployedResource `json:"frontend"`

	// Support サポートゾーン (3 スロット)、空き枠は null。
	Support []DeployedSupport `json:"support"`
}

// GameActionRequest POST /api/v1/games/{gameId}/actions のリクエスト body。
type GameActionRequest struct {
	ActionType string `json:"action_type"`

	// Data アクション固有の payload。サーバ側で action_type に応じて再パースされる。
	Data      map[string]interface{} `json:"data"`
	PlayerNum int64                  `json:"player_num"`
}

// GameCreatedResult NPC または PvP ゲーム作成時の battle server からの応答。
type GameCreatedResult struct {
	GameID string `json:"game_id"`
}

// GameOverEventData defines model for GameOverEventData.
type GameOverEventData struct {
	WinReason string `json:"winReason"`
	WinnerNum int64  `json:"winnerNum"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// HiddenDeployedSupport 表向き情報を隠蔽したサポートインスタンス。
type HiddenDeployedSupport struct {
	ArtNo int64 `json:"artNo"`

	// CardID カード ID (表向きの場合のみ含まれる)
	CardID     *string `json:"cardID,omitempty"`
	FaceDown   bool    `json:"faceDown"`
	InstanceID string  `json:"instanceID"`

	// Peeked 覗き見されたか
	Peeked bool `json:"peeked"`
}

// MonetizeEventData defines model for MonetizeEventData.
type MonetizeEventData struct {
	TotalAmount int64 `json:"totalAmount"`
}

// NpcBattleRequest POST /api/v1/games/npc のリクエスト body。
type NpcBattleRequest struct {
	DeckCards []BattleDeckCard `json:"deck_cards"`
	NpcModel  string           `json:"npc_model"`
}

// NpcModelEntry defines model for NpcModelEntry.
type NpcModelEntry struct {
	Difficulty  string `json:"difficulty"`
	DisplayName string `json:"display_name"`
	Faction     string `json:"faction"`
	Model       string `json:"model"`
}

// NpcModelsResponse defines model for NpcModelsResponse.
type NpcModelsResponse struct {
	Models []NpcModelEntry `json:"models"`
}

// OpponentField 相手のフィールド (サポートは非公開カード隠蔽)。
type OpponentField struct {
	Backend  []DeployedResource      `json:"backend"`
	Frontend []DeployedResource      `json:"frontend"`
	Support  []HiddenDeployedSupport `json:"support"`
}

// OpponentView 相手プレイヤー視点 (情報秘匿適用済み)。
type OpponentView struct {
	Budget int64 `json:"budget"`

	// Field 相手のフィールド (サポートは非公開カード隠蔽)。
	Field OpponentField `json:"field"`

	// HandCount 手札枚数 (内容は非公開)
	HandCount   int32            `json:"handCount"`
	InsightPool int64            `json:"insightPool"`
	PlayerNum   int64            `json:"playerNum"`
	RepoCount   int32            `json:"repoCount"`
	TimeBank    int64            `json:"timeBank"`
	Trash       []UndeployedCard `json:"trash"`
	TrashCount  int32            `json:"trashCount"`
}

// PhaseChangeEventData defines model for PhaseChangeEventData.
type PhaseChangeEventData struct {
	CurrentPhase  string `json:"currentPhase"`
	PreviousPhase string `json:"previousPhase"`
}

// PhaseEndEventData defines model for PhaseEndEventData.
type PhaseEndEventData struct {
	NeedsDiscard bool   `json:"needsDiscard"`
	Phase        string `json:"phase"`
}

// PlayCardEventData defines model for PlayCardEventData.
type PlayCardEventData struct {
	Cancelled *bool  `json:"cancelled,omitempty"`
	CardId    string `json:"cardId"`
	Index     int32  `json:"index"`
	Zone      string `json:"zone"`
}

// PlayerView 自プレイヤー視点のスナップショット。
type PlayerView struct {
	// AvailableActions 実行可能アクション一覧 (アクティブプレイヤーのみ)。
	AvailableActions *[]AvailableAction `json:"availableActions,omitempty"`
	Budget           int64              `json:"budget"`

	// Field 一方のプレイヤーのフィールド全体。
	Field       Field            `json:"field"`
	Hand        []UndeployedCard `json:"hand"`
	InsightPool int64            `json:"insightPool"`
	PlayerNum   int64            `json:"playerNum"`

	// RepoCount リポジトリ残り枚数
	RepoCount int32 `json:"repoCount"`

	// TimeBank タイムバンク (秒)
	TimeBank   int64            `json:"timeBank"`
	Trash      []UndeployedCard `json:"trash"`
	TrashCount int32            `json:"trashCount"`
}

// PvpBattleRequest POST /api/v1/games/pvp のリクエスト body。
type PvpBattleRequest struct {
	Deck1Cards []BattleDeckCard `json:"deck1_cards"`
	Deck2Cards []BattleDeckCard `json:"deck2_cards"`
}

// ReactiveRevealedEventData defines model for ReactiveRevealedEventData.
type ReactiveRevealedEventData struct {
	CardId     string `json:"cardId"`
	InstanceId string `json:"instanceId"`
}

// ScaleUpEventData defines model for ScaleUpEventData.
type ScaleUpEventData struct {
	InstanceFamily *string `json:"instanceFamily,omitempty"`
	InstanceId     string  `json:"instanceId"`
	TargetRank     string  `json:"targetRank"`
}

// SelectSlotEventData defines model for SelectSlotEventData.
type SelectSlotEventData struct {
	CardId     string `json:"cardId"`
	Index      int32  `json:"index"`
	InstanceId string `json:"instanceId"`
	Zone       string `json:"zone"`
}

// TemporaryEffect カードに付与されている一時効果。
type TemporaryEffect struct {
	// Duration 持続期間 (`until_end_of_turn` / `permanent` 等)。
	Duration   string `json:"duration"`
	EffectType string `json:"effectType"`

	// Mode バフモード (空文字=flat / `percent`=割合)
	Mode string `json:"mode"`

	// SourceID 効果の発生源インスタンス ID
	SourceID string `json:"sourceID"`
	Value    int64  `json:"value"`
}

// TurnControlsMessage 現在のターン操作可否を表すメッセージ。
type TurnControlsMessage struct {
	// CanEndPhase 現在のフェーズを終了できるか (main / battle フェーズで `true`)
	CanEndPhase bool `json:"canEndPhase"`

	// DiscardRequired 手札破棄が必要な枚数 (end フェーズで手札 > 6 枚の場合のみ > 0)
	DiscardRequired int32 `json:"discardRequired"`
}

// TurnEndEventData defines model for TurnEndEventData.
type TurnEndEventData struct {
	ActivePlayer int64  `json:"activePlayer"`
	CurrentPhase string `json:"currentPhase"`
	NextTurn     int64  `json:"nextTurn"`
	Phase        string `json:"phase"`
}

// TurnStartEventData defines model for TurnStartEventData.
type TurnStartEventData struct {
	IsMyTurn bool  `json:"is_my_turn"`
	Turn     int64 `json:"turn"`
}

// UndeployedCard 手札・トラッシュ等にあるカード。
type UndeployedCard struct {
	ArtNo      int64  `json:"artNo"`
	CardID     string `json:"cardID"`
	InstanceID string `json:"instanceID"`
}

// UseEffectEventData defines model for UseEffectEventData.
type UseEffectEventData struct {
	CardId   string  `json:"cardId"`
	SourceId string  `json:"sourceId"`
	TargetId *string `json:"targetId,omitempty"`
}

// GameIdPath defines model for GameIdPath.
type GameIdPath = string

// PlayerNumPath defines model for PlayerNumPath.
type PlayerNumPath = int32

// CreateNpcGameJSONRequestBody defines body for CreateNpcGame for application/json ContentType.
type CreateNpcGameJSONRequestBody = NpcBattleRequest

// CreatePvpGameJSONRequestBody defines body for CreatePvpGame for application/json ContentType.
type CreatePvpGameJSONRequestBody = PvpBattleRequest

// ProcessGameActionJSONRequestBody defines body for ProcessGameAction for application/json ContentType.
type ProcessGameActionJSONRequestBody = GameActionRequest
