using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Diagnostics;
using Npgsql;
using OverloadParty.Battle.Data;
using OverloadParty.Battle.Data.Json;
using OverloadParty.Battle.Data.Mock;
using OverloadParty.Battle.Data.Pg;
using OverloadParty.Battle.Engine;
using OverloadParty.Battle.Engine.Effects;
using OverloadParty.Battle.Engine.Processors;
using OverloadParty.Battle.Models;
using OverloadParty.Battle.Npc;
using OverloadParty.Battle.Service;
using OverloadParty.GameData;
// Disambiguate: ActionResult exists in both OverloadParty.Battle.Engine (internal engine result)
// and OverloadParty.GameData (wire envelope returned to the gateway).
using ActionResult = OverloadParty.GameData.ActionResult;

var builder = WebApplication.CreateBuilder(args);

// Determine mode
var isLocalDev = builder.Environment.IsDevelopment()
    || Environment.GetEnvironmentVariable("BATTLE_MODE") == "local";

builder.Services.AddLogging();

// Serialize enums as camelCase strings (e.g. Rank.Small → "small") so that
// downstream consumers (Gateway, client) receive strings instead of numeric values.
builder.Services.ConfigureHttpJsonOptions(options =>
{
    options.SerializerOptions.Converters.Add(
        new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower));
    options.SerializerOptions.Converters.Add(new ZoneJsonConverterFactory());
});

// ─── Data layer ─────────────────────────────────────────────

if (isLocalDev)
{
    // In-memory mock repositories
    var mockGameRepo = new MockGameRepository();

    builder.Services.AddSingleton<IGameRepository>(mockGameRepo);
    // ICardRepository registered after CardCache is built (below)
}
else
{
    // PostgreSQL repositories
    var connStr = builder.Configuration.GetConnectionString("DefaultConnection")
        ?? Environment.GetEnvironmentVariable("DATABASE_URL")
        ?? throw new InvalidOperationException("DATABASE_URL or ConnectionStrings:DefaultConnection not set");
    var dataSource = NpgsqlDataSource.Create(connStr);
    builder.Services.AddSingleton(dataSource);
    builder.Services.AddSingleton<IGameRepository>(sp => new PgGameRepository(sp.GetRequiredService<NpgsqlDataSource>()));
    builder.Services.AddSingleton<ICardRepository>(sp => new PgCardRepository(sp.GetRequiredService<NpgsqlDataSource>()));
}

// ─── Card cache ─────────────────────────────────────────────

var cardCache = new CardCache();
builder.Services.AddSingleton<ICardCache>(cardCache);
builder.Services.AddSingleton(cardCache);

if (isLocalDev)
{
    builder.Services.AddSingleton<ICardRepository>(new MockCardRepository(cardCache));
}

// ─── Engine ─────────────────────────────────────────────────

builder.Services.AddSingleton(sp =>
{
    var gameRepo = sp.GetRequiredService<IGameRepository>();
    var cc = sp.GetRequiredService<ICardCache>();
    var engine = new GameEngine(gameRepo, cc);

    // Initialize effects from card definitions (YAML-driven)
    var registry = new EffectRegistry();
    var customEffects = new CustomEffectRegistry();
    EffectYamlLoader.LoadFromCards(cc.All().Values, registry, customEffects);

    engine.SetEffectRegistry(registry);

    return engine;
});

// ─── Services ───────────────────────────────────────────────

var aiConfigDir = Environment.GetEnvironmentVariable("NPC_AI_CONFIG_DIR")
    ?? Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "src", "OverloadParty.Battle.Npc", "Data");
var aiConfigs = Directory.Exists(aiConfigDir)
    ? AiConfigLoader.LoadAll(aiConfigDir)
    : new Dictionary<string, AiConfig>();

builder.Services.AddSingleton<NpcRunner>(sp =>
    new NpcRunner(
        sp.GetRequiredService<GameEngine>(),
        sp.GetRequiredService<IGameRepository>(),
        sp.GetRequiredService<ICardCache>(),
        aiConfigs,
        sp.GetRequiredService<ILogger<NpcRunner>>()));

builder.Services.AddSingleton<GameService>(sp =>
    new GameService(
        sp.GetRequiredService<GameEngine>(),
        sp.GetRequiredService<IGameRepository>(),
        sp.GetRequiredService<ICardCache>(),
        sp.GetRequiredService<NpcRunner>(),
        aiConfigs));

builder.Services.AddSingleton<GameLogService>(sp =>
    new GameLogService(
        sp.GetRequiredService<IGameRepository>(),
        sp.GetRequiredService<ICardCache>()));

var app = builder.Build();

// ─── Load card cache ────────────────────────────────────────

if (isLocalDev)
{
    // Load cards from local JSON file (generated by common repo's generate_from_yaml.py)
    var cardsPath = Environment.GetEnvironmentVariable("CARDS_JSON_PATH")
        ?? Path.GetFullPath(Path.Combine(app.Environment.ContentRootPath,
            "..", "..", "..", "overload-party-common", "packages", "dotnet", "cache", "cards_gen.json"));
    if (!File.Exists(cardsPath))
    {
        throw new FileNotFoundException(
            $"Card data not found at {cardsPath}. Run 'python3 packages/generate_from_yaml.py --gen-dir packages/' in the common repo.");
    }
    var cards = JsonSerializer.Deserialize<List<CardDefinition>>(
        File.ReadAllText(cardsPath), new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
            PropertyNameCaseInsensitive = true,
        });
    if (cards is not null)
    {
        cardCache.LoadFromList(cards);
    }
    app.Logger.LogInformation("Loaded {Count} cards from {Path}", cardCache.Count, cardsPath);
}
else
{
    // Production: load cards from database
    var cardRepo = app.Services.GetRequiredService<ICardRepository>();
    await cardCache.LoadFromRepository(cardRepo);
    app.Logger.LogInformation("Loaded {Count} cards from database", cardCache.Count);
}

// ─── Middleware ──────────────────────────────────────────────

// CORS for development
if (isLocalDev)
{
    app.Use(async (context, next) =>
    {
        context.Response.Headers.Append("Access-Control-Allow-Origin", "*");
        context.Response.Headers.Append("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
        context.Response.Headers.Append("Access-Control-Allow-Headers", "Content-Type, Authorization");

        if (context.Request.Method == "OPTIONS")
        {
            context.Response.StatusCode = 204;
            return;
        }
        await next();
    });
}

// 例外を {"error": "..."} 形式のボディに統一してステータスコードを割り当てる。
// GameRuleException はルール違反として 400、それ以外は 500。
// Battle Server は Gateway からのみ呼ばれる内部サービスのため、500 時も ex.Message を透過する。
app.UseExceptionHandler(errorApp =>
{
    errorApp.Run(async context =>
    {
        var ex = context.Features.Get<IExceptionHandlerFeature>()?.Error;
        var (status, message) = ex switch
        {
            GameRuleException e => (StatusCodes.Status400BadRequest, e.Message),
            _ => (StatusCodes.Status500InternalServerError, ex?.Message ?? "internal error"),
        };
        if (status == StatusCodes.Status500InternalServerError)
        {
            app.Logger.LogError(ex, "Unexpected error");
        }
        context.Response.StatusCode = status;
        await context.Response.WriteAsJsonAsync(new { error = message });
    });
});

// ─── Routes ─────────────────────────────────────────────────

app.MapGet("/health", () => Results.Ok(new { status = "ok" }));

// ─── REST API Endpoints ─────────────────────────────────────

// JSON options used to convert engine-native payloads (Dictionary<string, object>, ClientGameState)
// into JsonElement for the generated ActionEvent envelope. Must mirror the HTTP serializer options
// (JsonStringEnumConverter + ZoneJsonConverterFactory) so the wire format is byte-identical to the
// previous anonymous-type projection.
var envelopeJsonOptions = new JsonSerializerOptions
{
    Converters =
    {
        new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower),
        new ZoneJsonConverterFactory(),
    },
};

var api = app.MapGroup("/api/v1");

// NPC Models
api.MapGet("/npc/models", () =>
{
    var models = aiConfigs.Values.Select(c => new
    {
        model = c.Model,
        faction = c.Faction,
        difficulty = c.Model[(c.Faction.Length + 1)..],
        display_name = c.DisplayName,
    });
    return Results.Ok(new { models });
});

// NPC Game Creation
api.MapPost("/games/npc", async (GameService gameSvc, NpcBattleRequest req) =>
{
    var cards = req.Cards.Select(c => new DeckSnapshotCard { CardId = c.CardID, ArtNo = c.ArtNo }).ToList();
    var game = await gameSvc.StartNPCBattle(req.PlayerID, req.DeckID, cards, req.NpcModel);
    return Results.Ok(new { game_id = game.GameID, player1_id = game.Player1ID, player2_id = game.Player2ID, npc1_model = game.Npc1Model, npc2_model = game.Npc2Model });
});

// PvP Game Creation (called by Gateway after matchmaking)
api.MapPost("/games/pvp", async (GameService gameSvc, PvpBattleRequest req) =>
{
    var p1Cards = req.Player1Cards.Select(c => new DeckSnapshotCard { CardId = c.CardID, ArtNo = c.ArtNo }).ToList();
    var p2Cards = req.Player2Cards.Select(c => new DeckSnapshotCard { CardId = c.CardID, ArtNo = c.ArtNo }).ToList();
    var game = await gameSvc.CreateGameFromMatch(req.Player1ID, req.Player1DeckID, p1Cards, req.Player2ID, req.Player2DeckID, p2Cards);
    return Results.Ok(new { game_id = game.GameID, player1_id = game.Player1ID, player2_id = game.Player2ID });
});

// Game Action
api.MapPost("/games/{gameId}/actions", async (GameService gameSvc, string gameId, GameActionRequest req) =>
{
    var actionType = EnumExtensions.ParseActionType(req.ActionType);
    var actionData = ActionDataDeserializer.Deserialize(actionType, req.Data);
    var result = await gameSvc.ProcessAction(gameId, req.PlayerID, actionType, actionData);
    return Results.Ok(ProjectActionResult(result));
});

// Advance NPC Turn
// Called by the gateway after game_enter to run the NPC's first turn
// so that action events can be delivered via WebSocket.
api.MapPost("/games/{gameId}/advance-npc", async (GameService gameSvc, string gameId, NpcAdvanceRequest req) =>
{
    var result = await gameSvc.AdvanceNpcTurn(gameId, req.PlayerID);
    return Results.Ok(ProjectActionResult(result));
});

// Game State Retrieval
api.MapGet("/games/{gameId}/state/{playerId}", async (GameService gameSvc, string gameId, string playerId) =>
{
    var state = await gameSvc.GetGameStateForPlayer(gameId, playerId);
    return Results.Ok(state);
});

// Turn Controls Retrieval
api.MapGet("/games/{gameId}/controls/{playerId}", async (GameService gameSvc, string gameId, string playerId) =>
{
    var controls = await gameSvc.GetTurnControlsForPlayer(gameId, playerId);
    return Results.Ok(controls);
});

// Game Log (Replay)
api.MapGet("/games/{gameId}/log", async (GameLogService logSvc, string gameId) =>
{
    var log = await logSvc.GetGameLog(gameId);
    if (log is null) return Results.NotFound(new { error = "game not found" });
    return Results.Bytes(logSvc.SerializeToJson(log), "application/json");
});

api.MapGet("/games/{gameId}/log/text", async (GameLogService logSvc, string gameId) =>
{
    var text = await logSvc.GetGameLogText(gameId);
    if (text is null) return Results.NotFound(new { error = "game not found" });
    return Results.Text(text, "text/plain");
});

// Dev REST API endpoints (local mode only)
if (isLocalDev)
{
    app.MapGet("/api/dev/cards", (ICardCache cc) =>
        Results.Ok(cc.All().Values.Select(c => new { c.CardId, c.CardName, c.Faction, c.CardType })));
}

var port = Environment.GetEnvironmentVariable("PORT") ?? "9002";
app.Urls.Add($"http://0.0.0.0:{port}");

app.Logger.LogInformation("Battle server starting on port {Port} (mode={Mode})",
    port, isLocalDev ? "local" : "production");

app.Run();

ActionResult ProjectActionResult(GameActionResult result) => new()
{
    GameOver = result.GameOver is not null,
    WinnerNum = result.GameOver?.WinnerNum ?? 0,
    WinReason = result.GameOver?.Reason ?? "",
    NpcPending = result.NpcPending,
    Events = result.Events.Select(e => new ActionEvent
    {
        Sequence = e.Event.SequenceNumber,
        EventType = e.Event.EventType,
        PlayerID = e.Event.PlayerID ?? "",
        IsSystem = e.Event.IsSystemEvent,
        EventData = JsonSerializer.SerializeToElement(e.Event.EventData, envelopeJsonOptions),
        State = JsonSerializer.SerializeToElement(e.State, envelopeJsonOptions),
    }).ToList(),
};

public static class ActionDataDeserializer
{
    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        PropertyNameCaseInsensitive = true,
    };

    public static object Deserialize(ActionType actionType, JsonElement data) => actionType switch
    {
        ActionType.PlayCard => data.Deserialize<PlayCardRequest>(JsonOpts)!,
        ActionType.Attack => data.Deserialize<AttackRequest>(JsonOpts)!,
        ActionType.ScaleUp => data.Deserialize<ScaleUpRequest>(JsonOpts)!,
        ActionType.Monetize => data.Deserialize<MonetizeRequest>(JsonOpts)!,
        ActionType.DiscardHand => data.Deserialize<DiscardHandRequest>(JsonOpts)!,
        ActionType.UseEffect => data.Deserialize<UseEffectRequest>(JsonOpts)!,
        ActionType.EndPhase => new object(),
        ActionType.Forfeit => data.Deserialize<ForfeitRequest>(JsonOpts)!,
        _ => throw new ArgumentException($"unknown action type: {actionType}"),
    };
}
