<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OverloadParty.Battle.Models\OverloadParty.Battle.Models.csproj" />
    <ProjectReference Include="..\OverloadParty.Battle.Engine\OverloadParty.Battle.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.71.0" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="OverloadParty.ApiCard" Version="0.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
