#!/usr/bin/env python3
"""Generate battle-owned constants, event data types, and models from YAML.

ADR-015 Phase 6 / ADR-014: battle repo が所有するのは以下のみ。
common で同様の役割を持っていた generate_types.py を battle 向けに
剥がしたバージョン。

Inputs (SSoT, this repo):
  - data/game_logic_constants.yaml  (Phase / WinReason / EventType 等)
  - data/event_schemas.yaml         (EventType ごとの payload 定義)
  - data/models.yaml                (battle_gateway_rpc + game_state_view + variant_types)

Outputs (Go — each directory is an independent module):
  - packages/game-logic-constants-go/constants_gen.go
  - packages/api-battle-rpc-go/battle_gateway_rpc_gen.go

Outputs (C# — each directory is an independent NuGet csproj):
  - packages/game-logic-constants-dotnet/GameLogicConstants_gen.cs
      (namespace OverloadParty.GameLogicConstants)
  - packages/game-state-dotnet/{EventData,GameStateView,VariantTypes}_gen.cs
      (namespace OverloadParty.GameState; also embeds cache/cards_gen.json
       which is produced by common's generate_cards.py and shipped as a
       checked-in binary here)
  - packages/api-battle-rpc-dotnet/BattleGatewayRpc_gen.cs
      (namespace OverloadParty.ApiBattleRpc)

Outputs (TS — each directory is an independent npm package):
  - packages/game-logic-constants-npm/src/index.ts
  - packages/game-state-npm/src/{models,eventData,variantTypes,index}.ts

Usage:
    python3 scripts/generate_types.py
"""

import json
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# ─── Paths ──────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"

GAME_LOGIC_YAML = DATA_DIR / "game_logic_constants.yaml"
EVENT_SCHEMAS_YAML = DATA_DIR / "event_schemas.yaml"
MODELS_YAML = DATA_DIR / "models.yaml"

PACKAGES_DIR = ROOT / "packages"
# Go module directories (one per logical package).
GO_GAME_LOGIC_DIR = PACKAGES_DIR / "game-logic-constants-go"
GO_API_BATTLE_RPC_DIR = PACKAGES_DIR / "api-battle-rpc-go"

# C# csproj directories.
DOTNET_GAME_LOGIC_DIR = PACKAGES_DIR / "game-logic-constants-dotnet"
DOTNET_GAME_STATE_DIR = PACKAGES_DIR / "game-state-dotnet"
DOTNET_API_BATTLE_RPC_DIR = PACKAGES_DIR / "api-battle-rpc-dotnet"

# npm package directories.
NPM_GAME_LOGIC_DIR = PACKAGES_DIR / "game-logic-constants-npm"
NPM_GAME_STATE_DIR = PACKAGES_DIR / "game-state-npm"

# models.yaml section → (Go module dir, Go package name).
_GO_MODELS_ROUTING = {
    "battle_gateway_rpc": (GO_API_BATTLE_RPC_DIR, "apibattle"),
}

# ─── Helpers ────────────────────────────────────────────

_GENERATED_HEADER = "// Code generated by scripts/generate_types.py; DO NOT EDIT."


def _snake_to_pascal(s):
    return "".join(w.title() for w in s.split("_"))


def _camel_to_pascal(s):
    return s[0].upper() + s[1:]


def _to_pascal(value):
    value = value.replace("/", "")
    if "_" in value or "-" in value:
        return "".join(w.title() for w in value.replace("-", "_").split("_"))
    if value and value[0].isupper():
        return value
    return value.title() if value else value


# ─── Simple list descriptors ────────────────────────────
# (yaml_key, go_prefix, go_comment, cs_class, ts_const, ts_type, extra_union)

GAME_LOGIC_SIMPLE = [
    ("phases", "Phase", "Phases", "Phases", "PHASES", "GamePhase", "'selecting'"),
    ("game_status", "GameStatus", "Game status", "GameStatus", "GAME_STATUS", "GameStatus", None),
    ("win_reasons", "WinReason", "Win reasons", "WinReasons", "WIN_REASONS", "WinReason", None),
    ("action_types", "ActionType", "Action types", "ActionTypes", "ACTION_TYPES", "GameActionType", None),
    ("event_types", "EventType", "Event types", "EventTypes", "EVENT_TYPES", "EventType", None),
    ("effect_durations", "EffectDuration", "Effect durations", "EffectDurations", "EFFECT_DURATIONS", "EffectDuration", None),
    ("trigger_types", "TriggerType", "Trigger types", "TriggerTypes", "TRIGGER_TYPES", "TriggerType", None),
    ("effect_ops", "EffectOp", "Effect operations", "EffectOps", "EFFECT_OPS", "EffectOp", None),
    ("buff_types", "BuffType", "Buff types", "BuffTypes", "BUFF_TYPES", "BuffType", None),
    ("buff_modes", "BuffMode", "Buff modes", "BuffModes", "BUFF_MODES", "BuffMode", None),
    ("custom_effects", "CustomEffect", "Custom effects", "CustomEffects", "CUSTOM_EFFECTS", "CustomEffect", None),
    ("effect_categories", "EffectCategory", "Effect categories", "EffectCategories", "EFFECT_CATEGORIES", "EffectCategory", None),
    ("effect_target_types", "EffectTargetType", "Effect target types", "EffectTargetTypes", "EFFECT_TARGET_TYPES", "EffectTargetType", None),
    ("player_refs", "PlayerRef", "Player references", "PlayerRefs", "PLAYER_REFS", "PlayerRef", None),
    ("use_limits", "UseLimit", "Use limits", "UseLimits", "USE_LIMITS", "UseLimit", None),
    ("guard_types", "GuardType", "Guard types", "GuardTypes", "GUARD_TYPES", "GuardType", None),
    ("selector_pick_modes", "SelectorPickMode", "Selector pick modes", "SelectorPickModes", "SELECTOR_PICK_MODES", "SelectorPickMode", None),
]


# ─── Go: generic emitters ───────────────────────────────
def _go_const_block(comment, prefix, values):
    lines = [f"// {comment}."]
    lines.append("const (")
    for v in values:
        name = f"{prefix}{_to_pascal(v)}"
        lines.append(f'\t{name} = "{v}"')
    lines.append(")")
    lines.append("")
    return lines


def _go_header(package):
    return [
        _GENERATED_HEADER,
        "",
        f"package {package}",
        "",
    ]


def _write_file(out_path, lines):
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── Go: game_logic module ─────────────────────────────
def generate_go_game_logic(data):
    lines = _go_header("game_logic")
    for yaml_key, go_prefix, go_comment, _, _, _, _ in GAME_LOGIC_SIMPLE:
        values = data.get(yaml_key)
        if values is None:
            continue
        lines.extend(_go_const_block(go_comment, go_prefix, values))
    _write_file(GO_GAME_LOGIC_DIR / "constants_gen.go", lines)


# ─── Go: models (battle_gateway_rpc) ────────────────────
def _go_type_needs_import(type_str):
    imports = set()
    if "time.Time" in type_str or "time." in type_str:
        imports.add("time")
    if "json.RawMessage" in type_str:
        imports.add("encoding/json")
    return imports


def _generate_go_model_file(file_def, *, out_path, package_name):
    lines = [
        _GENERATED_HEADER,
        "",
        f"package {package_name}",
        "",
    ]

    declared_imports = set(file_def.get("imports", []))
    for td in file_def.get("types", []):
        for field in td.get("fields", []):
            declared_imports |= _go_type_needs_import(str(field["type"]))

    if declared_imports:
        std_imports = sorted(i for i in declared_imports if "." not in i.split("/")[0])
        ext_imports = sorted(i for i in declared_imports if "." in i.split("/")[0])
        lines.append("import (")
        for imp in std_imports:
            lines.append(f'\t"{imp}"')
        if std_imports and ext_imports:
            lines.append("")
        for imp in ext_imports:
            lines.append(f'\t"{imp}"')
        lines.append(")")
        lines.append("")

    for td in file_def.get("types", []):
        if td.get("comment"):
            lines.append(f"// {td['comment']}")
        lines.append(f"type {td['name']} struct {{")

        fields = td.get("fields", [])
        if fields:
            max_name_len = max(len(f["name"]) for f in fields)
            max_type_len = max(len(str(f["type"])) for f in fields)

        for field in fields:
            fname = field["name"]
            ftype = str(field["type"])
            tags = []
            if "json" in field:
                tags.append(f'json:"{field["json"]}"')
            if "db" in field:
                tags.append(f'db:"{field["db"]}"')
            tag_str = " ".join(tags)

            name_pad = " " * (max_name_len - len(fname) + 1)
            type_pad = " " * (max_type_len - len(ftype) + 1)

            if tag_str:
                line = f"\t{fname}{name_pad}{ftype}{type_pad}`{tag_str}`"
            else:
                line = f"\t{fname}{name_pad}{ftype}"

            if field.get("comment"):
                line += f" // {field['comment']}"
            lines.append(line)

        lines.append("}")
        lines.append("")

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


def generate_go_models():
    with open(MODELS_YAML, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    emitted = {}

    for file_def in data["files"]:
        if file_def.get("go_skip"):
            continue

        name = file_def["name"]
        route = _GO_MODELS_ROUTING.get(name)
        if route is None:
            continue

        module_dir, package_name = route
        out_path = module_dir / f"{name}_gen.go"
        _generate_go_model_file(file_def, out_path=out_path, package_name=package_name)
        emitted.setdefault(module_dir, []).append(name)

    return emitted


# ─── C# constants: generic emitters ────────────────────
def _cs_static_class(class_name, values, indent="    "):
    lines = [f"public static class {class_name}"]
    lines.append("{")
    for v in values:
        name = _to_pascal(v)
        lines.append(f'{indent}public const string {name} = "{v}";')
    lines.append("}")
    lines.append("")
    return lines


def _cs_header(namespace):
    return [
        _GENERATED_HEADER,
        "",
        f"namespace {namespace};",
        "",
    ]


# ─── C#: game_logic namespace ──────────────────────────
def generate_csharp_game_logic(data):
    lines = _cs_header("OverloadParty.GameLogicConstants")
    for yaml_key, _, _, cs_class, _, _, _ in GAME_LOGIC_SIMPLE:
        values = data.get(yaml_key)
        if values is None:
            continue
        lines.extend(_cs_static_class(cs_class, values))
    _write_file(DOTNET_GAME_LOGIC_DIR / "GameLogicConstants_gen.cs", lines)


# ─── C# (event data) ───────────────────────────────────
_CS_TYPE_MAP = {
    "string": "string",
    "int": "int",
    "long": "long",
    "bool": "bool",
    "string[]": "List<string>",
}

_CS_NULLABLE_DEFAULTS = {
    "string": "string?",
    "int": "int?",
    "long": "long?",
    "bool": "bool?",
    "string[]": "List<string>?",
}


def generate_csharp_event_data(schemas, *, out_path, namespace="OverloadParty.GameState"):
    cs_out = Path(out_path)

    lines = [
        _GENERATED_HEADER,
        "",
        f"namespace {namespace};",
        "",
        "/// <summary>Marker interface for all EventData records. Used to constrain GameEvent.EventData type.</summary>",
        "public interface IEventData { }",
        "",
    ]

    for event_type, fields in schemas.items():
        if event_type.startswith("_"):
            continue

        class_name = f"{_snake_to_pascal(event_type)}EventData"
        lines.append(f"public class {class_name} : IEventData")
        lines.append("{")

        optional_fields = []

        for raw_key, raw_type in fields.items():
            optional = raw_key.endswith("?")
            key = raw_key.rstrip("?")
            cs_prop = _snake_to_pascal(key) if "_" in key else _camel_to_pascal(key)

            if optional:
                cs_type = _CS_NULLABLE_DEFAULTS[raw_type]
                optional_fields.append((cs_prop, cs_type))
            else:
                cs_type = _CS_TYPE_MAP[raw_type]
                init = ' = "";' if raw_type == "string" else " = [];" if raw_type == "string[]" else ""
                lines.append(f"    public required {cs_type} {cs_prop} {{ get; init; }}{init}")

        for cs_prop, cs_type in optional_fields:
            lines.append(f"    public {cs_type} {cs_prop} {{ get; init; }}")

        lines.append("}")
        lines.append("")

    cs_out.parent.mkdir(parents=True, exist_ok=True)
    with open(cs_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── C# (game state view) ─────────────────────────────
_GO_TO_CS_TYPE = {
    "string": "string",
    "int": "int",
    "int64": "long",
    "bool": "bool",
    "time.Time": "DateTime",
    "json.RawMessage": "JsonElement?",
}


def _go_to_cs_type(go_type):
    is_pointer = go_type.startswith("*")
    base = go_type.lstrip("*")

    if base.startswith("[]*"):
        elem = base[3:]
        cs_elem = _GO_TO_CS_TYPE.get(elem, elem)
        return f"{cs_elem}?[]"

    if base.startswith("[]"):
        elem = base[2:]
        cs_elem = _GO_TO_CS_TYPE.get(elem, elem)
        return f"{cs_elem}[]"

    cs_base = _GO_TO_CS_TYPE.get(base, base)

    if is_pointer:
        return f"{cs_base}?"

    return cs_base


def generate_csharp_game_state_view(*, out_path, namespace="OverloadParty.GameState"):
    with open(MODELS_YAML, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    file_def = None
    for fd in data["files"]:
        if fd["name"] == "game_state_view":
            file_def = fd
            break

    if file_def is None:
        raise RuntimeError("game_state_view not found in models.yaml")

    cs_out = Path(out_path)

    lines = [
        _GENERATED_HEADER,
        "",
        f"namespace {namespace};",
        "",
    ]

    for td in file_def.get("types", []):
        name = td["name"]
        if td.get("comment"):
            lines.append(f"/// <summary>{td['comment']}</summary>")
        lines.append(f"public class {name}")
        lines.append("{")

        for field in td.get("fields", []):
            go_type = str(field["type"])
            json_tag = str(field.get("json", ""))
            has_omitempty = json_tag.endswith(",omitempty")
            cs_type = _go_to_cs_type(go_type)
            fname = field["name"]

            is_custom_ref = cs_type not in _GO_TO_CS_TYPE.values() and not cs_type.endswith("?") and not cs_type.endswith("[]")

            if go_type.startswith("*"):
                lines.append(f"    public {cs_type} {fname} {{ get; init; }}")
            elif go_type.startswith("[]"):
                if has_omitempty:
                    lines.append(f"    public {cs_type}? {fname} {{ get; init; }}")
                else:
                    lines.append(f"    public {cs_type} {fname} {{ get; init; }} = [];")
            elif is_custom_ref:
                lines.append(f"    public required {cs_type} {fname} {{ get; init; }}")
            elif cs_type == "string":
                lines.append(f'    public {cs_type} {fname} {{ get; init; }} = "";')
            else:
                lines.append(f"    public {cs_type} {fname} {{ get; init; }}")

        lines.append("}")
        lines.append("")

    cs_out.parent.mkdir(parents=True, exist_ok=True)
    with open(cs_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── C# (battle ↔ gateway RPC envelope) ──────────────
_GO_TO_CS_ENVELOPE_TYPE = {
    "string": "string",
    "int": "int",
    "int64": "long",
    "bool": "bool",
    "time.Time": "DateTime",
    "json.RawMessage": "JsonElement",
}


def _go_to_cs_envelope_type(go_type):
    is_pointer = go_type.startswith("*")
    base = go_type.lstrip("*")

    if base.startswith("[]"):
        elem = base[2:]
        cs_elem = _GO_TO_CS_ENVELOPE_TYPE.get(elem, elem)
        return f"List<{cs_elem}>"

    cs_base = _GO_TO_CS_ENVELOPE_TYPE.get(base, base)

    if is_pointer:
        return f"{cs_base}?"

    return cs_base


def generate_csharp_battle_gateway_rpc(*, out_path, namespace="OverloadParty.ApiBattleRpc"):
    with open(MODELS_YAML, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    file_def = None
    for fd in data["files"]:
        if fd["name"] == "battle_gateway_rpc":
            file_def = fd
            break

    if file_def is None:
        raise RuntimeError("battle_gateway_rpc not found in models.yaml")

    cs_out = Path(out_path)

    lines = [
        _GENERATED_HEADER,
        "",
        "using System.Text.Json;",
        "using System.Text.Json.Serialization;",
        "",
        f"namespace {namespace};",
        "",
    ]

    for td in file_def.get("types", []):
        name = td["name"]
        is_request = name.endswith("Request")

        if td.get("comment"):
            lines.append(f"/// <summary>{td['comment']}</summary>")

        if is_request:
            fields = td.get("fields", [])
            if not fields:
                lines.append(f"public record {name}();")
                lines.append("")
                continue

            lines.append(f"public record {name}(")
            for i, field in enumerate(fields):
                go_type = str(field["type"])
                json_tag = str(field.get("json", ""))
                json_key = json_tag.split(",")[0]
                cs_type = _go_to_cs_envelope_type(go_type)
                fname = field["name"]
                trailing = "," if i < len(fields) - 1 else ");"
                lines.append(f'    [property: JsonPropertyName("{json_key}")] {cs_type} {fname}{trailing}')
            lines.append("")
        else:
            lines.append(f"public class {name}")
            lines.append("{")
            for field in td.get("fields", []):
                go_type = str(field["type"])
                json_tag = str(field.get("json", ""))
                json_key = json_tag.split(",")[0]
                has_omitempty = json_tag.endswith(",omitempty")
                cs_type = _go_to_cs_envelope_type(go_type)
                fname = field["name"]

                lines.append(f'    [JsonPropertyName("{json_key}")]')
                if go_type.startswith("*"):
                    lines.append(f"    public {cs_type} {fname} {{ get; init; }}")
                elif go_type.startswith("[]"):
                    if has_omitempty:
                        lines.append(f"    public {cs_type}? {fname} {{ get; init; }}")
                    else:
                        lines.append(f"    public {cs_type} {fname} {{ get; init; }} = [];")
                elif cs_type == "string":
                    lines.append(f'    public {cs_type} {fname} {{ get; init; }} = "";')
                else:
                    lines.append(f"    public {cs_type} {fname} {{ get; init; }}")
            lines.append("}")
            lines.append("")

    cs_out.parent.mkdir(parents=True, exist_ok=True)
    with open(cs_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── C# (variant types) ───────────────────────────────
def generate_csharp_variant_types(variant_types, *, out_path, namespace="OverloadParty.GameState"):
    cs_out = Path(out_path)

    lines = [
        _GENERATED_HEADER,
        "",
        f"namespace {namespace};",
        "",
    ]

    for vt in variant_types:
        name = vt["name"]
        discriminator = vt["discriminator"]
        disc_prop = _snake_to_pascal(discriminator)

        if vt.get("comment"):
            lines.append(f"/// <summary>{vt['comment']}</summary>")

        lines.append(f"public class {name}")
        lines.append("{")

        lines.append(f'    public required string {disc_prop} {{ get; init; }} = "";')

        seen = {}
        for variant in vt["variants"]:
            for field in variant.get("fields", []):
                fname = field["name"]
                if fname in seen:
                    continue
                cs_prop = _camel_to_pascal(fname)
                raw_type = field["type"]
                cs_type = _CS_NULLABLE_DEFAULTS[raw_type]
                seen[fname] = (cs_prop, cs_type)

        for cs_prop, cs_type in seen.values():
            lines.append(f"    public {cs_type} {cs_prop} {{ get; init; }}")

        lines.append("}")
        lines.append("")

    cs_out.parent.mkdir(parents=True, exist_ok=True)
    with open(cs_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── TS constants: generic emitters ────────────────────
def _ts_const_array(const_name, type_name, values, extra_union=None):
    lines = []
    lines.append(f"export const {const_name} = {json.dumps(values)} as const;")
    if extra_union:
        lines.append(f"export type {type_name} = (typeof {const_name})[number] | {extra_union};")
    else:
        lines.append(f"export type {type_name} = (typeof {const_name})[number];")
    lines.append("")
    return lines


def _ts_header():
    return [
        _GENERATED_HEADER,
        "",
    ]


def _write_ts_index(out_path, module_names):
    lines = [_GENERATED_HEADER]
    for name in module_names:
        lines.append(f"export * from './{name}';")
    _write_file(Path(out_path), lines)


# ─── TS: game-logic-constants-npm ──────────────────────
def generate_ts_game_logic(data):
    lines = _ts_header()
    for yaml_key, _, _, _, ts_const, ts_type, extra_union in GAME_LOGIC_SIMPLE:
        values = data.get(yaml_key)
        if values is None:
            continue
        lines.extend(_ts_const_array(ts_const, ts_type, values, extra_union=extra_union))
    _write_file(NPM_GAME_LOGIC_DIR / "src" / "index.ts", lines)


# ─── TS (event data) ──────────────────────────────────
_TS_TYPE_MAP = {
    "string": "string",
    "int": "number",
    "long": "number",
    "bool": "boolean",
    "string[]": "string[]",
}


def generate_ts_event_data(schemas, *, out_path):
    ts_out = Path(out_path)

    lines = [
        _GENERATED_HEADER,
        "",
    ]

    type_names = []

    for event_type, fields in schemas.items():
        if event_type.startswith("_"):
            continue

        type_name = f"{_snake_to_pascal(event_type)}EventData"
        type_names.append((event_type, type_name))

        lines.append(f"export interface {type_name} {{")
        for raw_key, raw_type in fields.items():
            optional = raw_key.endswith("?")
            key = raw_key.rstrip("?")
            ts_type = _TS_TYPE_MAP[raw_type]
            opt = "?" if optional else ""
            lines.append(f"  {key}{opt}: {ts_type};")
        lines.append("}")
        lines.append("")

    lines.append("export interface EventDataMap {")
    for event_type, type_name in type_names:
        lines.append(f"  {event_type}: {type_name};")
    lines.append("}")
    lines.append("")

    ts_out.parent.mkdir(parents=True, exist_ok=True)
    with open(ts_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── TS (models) ──────────────────────────────────────
_GO_TO_TS_MODEL_TYPE = {
    "string": "string",
    "int": "number",
    "int64": "number",
    "bool": "boolean",
    "time.Time": "string",
    "json.RawMessage": "Record<string, unknown>",
    "interface{}": "unknown",
    "map[string]interface{}": "Record<string, unknown>",
}


def _go_to_ts_model_field(go_type, json_tag, type_map=None, *, nullable_as_optional=False):
    if type_map is None:
        type_map = _GO_TO_TS_MODEL_TYPE
    optional = json_tag.endswith(",omitempty")
    json_key = json_tag.split(",")[0]

    is_pointer = go_type.startswith("*")
    base_type = go_type.lstrip("*")

    if base_type.startswith("[]*"):
        elem = base_type[3:]
        ts_elem = type_map.get(elem, elem)
        ts_type = f"({ts_elem} | null)[]"
        return json_key, ts_type, optional

    if base_type.startswith("[]"):
        elem = base_type[2:]
        ts_elem = type_map.get(elem, elem)
        ts_type = f"{ts_elem}[]"
        return json_key, ts_type, optional

    if base_type.startswith("map["):
        ts_type = type_map.get(base_type, "Record<string, unknown>")
        return json_key, ts_type, optional

    ts_base = type_map.get(base_type, base_type)

    if is_pointer:
        if optional:
            return json_key, ts_base, True
        elif nullable_as_optional:
            return json_key, ts_base, True
        else:
            return json_key, f"{ts_base} | null", False

    return json_key, ts_base, optional


def generate_ts_models():
    with open(MODELS_YAML, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    alias_map = dict(_GO_TO_TS_MODEL_TYPE)
    for file_def in data["files"]:
        for ta in file_def.get("type_aliases", []):
            base = ta["base"]
            alias_map[ta["name"]] = _GO_TO_TS_MODEL_TYPE.get(base, base)

    # Only game_state_view is routed to a TS package in battle repo.
    target_file = None
    for file_def in data["files"]:
        if file_def["name"] == "game_state_view":
            target_file = file_def
            break
    if target_file is None:
        return

    file_nullable_as_optional = target_file.get("nullable_as_optional", False)

    lines = [
        _GENERATED_HEADER,
        "",
    ]

    ts_imports: dict[str, list[str]] = {}
    for imp in target_file.get("ts_imports", []):
        from_path = imp["from"]
        for name in imp["names"]:
            ts_imports.setdefault(from_path, []).append(name)

    for from_path, names in sorted(ts_imports.items()):
        sorted_names = sorted(set(names))
        lines.append(f"import type {{ {', '.join(sorted_names)} }} from '{from_path}';")
    if ts_imports:
        lines.append("")

    for td in target_file.get("types", []):
        name = td["name"]
        if td.get("comment"):
            lines.append(f"/** {td['comment']} */")
        lines.append(f"export interface {name} {{")
        for field in td.get("fields", []):
            go_type = str(field["type"])
            json_tag = field["json"]
            json_key, ts_type, optional = _go_to_ts_model_field(
                go_type, json_tag, alias_map,
                nullable_as_optional=file_nullable_as_optional,
            )
            if "ts_type" in field:
                ts_type = field["ts_type"]
            if "ts_optional" in field:
                optional = field["ts_optional"]
            opt = "?" if optional else ""
            lines.append(f"  {json_key}{opt}: {ts_type};")
        lines.append("}")
        lines.append("")

    out_path = NPM_GAME_STATE_DIR / "src" / "models.ts"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── TS (variant types) ───────────────────────────────
def generate_ts_variant_types(variant_types, *, out_path):
    """AvailableAction は game-design-constants から Rank / InstanceFamily を import する."""
    ts_out = Path(out_path)

    ref_types: set[str] = set()
    for vt in variant_types:
        for variant in vt.get("variants", []):
            for field in variant.get("fields", []):
                ref = field.get("ref")
                if ref:
                    ref_types.add(ref)

    lines = [
        _GENERATED_HEADER,
        "",
    ]

    if ref_types:
        sorted_refs = sorted(ref_types)
        lines.append(
            f"import type {{ {', '.join(sorted_refs)} }} from '@kenyamaneko/overload-party-game-design-constants';"
        )
        lines.append("")

    for vt in variant_types:
        name = vt["name"]
        discriminator = vt["discriminator"]

        if vt.get("comment"):
            lines.append(f"/** {vt['comment']} */")

        variant_lines = []
        for variant in vt["variants"]:
            value = variant["value"]
            fields = [f"{discriminator}: '{value}'"]
            for field in variant.get("fields", []):
                fname = field["name"]
                ref = field.get("ref")
                ts_type = ref if ref else _TS_TYPE_MAP[field["type"]]
                opt = "?" if field.get("optional") else ""
                fields.append(f"{fname}{opt}: {ts_type}")
            variant_lines.append("  | { " + "; ".join(fields) + " }")

        lines.append(f"export type {name} =")
        for vl in variant_lines:
            lines.append(vl)
        lines[-1] = lines[-1] + ";"
        lines.append("")

    ts_out.parent.mkdir(parents=True, exist_ok=True)
    with open(ts_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── Main ─────────────────────────────────────────────
def _load_yaml(path):
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def main():
    game_logic = _load_yaml(GAME_LOGIC_YAML)
    event_schemas = _load_yaml(EVENT_SCHEMAS_YAML)
    models = _load_yaml(MODELS_YAML)
    variant_types = models.get("variant_types", [])

    # ── Go constants + models ──
    generate_go_game_logic(game_logic)
    print("Generated → packages/game-logic-constants-go/constants_gen.go", file=sys.stderr)

    emitted = generate_go_models()
    for module_dir, names in emitted.items():
        rel = module_dir.relative_to(ROOT)
        print(f"Generated models → {rel}/ [{', '.join(names)}]", file=sys.stderr)

    # ── C# csproj ──
    generate_csharp_game_logic(game_logic)
    print("Generated → packages/game-logic-constants-dotnet/GameLogicConstants_gen.cs", file=sys.stderr)

    generate_csharp_event_data(event_schemas, out_path=DOTNET_GAME_STATE_DIR / "EventData_gen.cs")
    print("Generated → packages/game-state-dotnet/EventData_gen.cs", file=sys.stderr)

    if variant_types:
        generate_csharp_variant_types(variant_types, out_path=DOTNET_GAME_STATE_DIR / "VariantTypes_gen.cs")
        print("Generated → packages/game-state-dotnet/VariantTypes_gen.cs", file=sys.stderr)

    generate_csharp_game_state_view(out_path=DOTNET_GAME_STATE_DIR / "GameStateView_gen.cs")
    print("Generated → packages/game-state-dotnet/GameStateView_gen.cs", file=sys.stderr)

    generate_csharp_battle_gateway_rpc(out_path=DOTNET_API_BATTLE_RPC_DIR / "BattleGatewayRpc_gen.cs")
    print("Generated → packages/api-battle-rpc-dotnet/BattleGatewayRpc_gen.cs", file=sys.stderr)

    # ── TypeScript ──
    generate_ts_game_logic(game_logic)
    print("Generated → packages/game-logic-constants-npm/src/index.ts", file=sys.stderr)

    generate_ts_models()
    print("Generated → packages/game-state-npm/src/models.ts", file=sys.stderr)

    generate_ts_event_data(event_schemas, out_path=NPM_GAME_STATE_DIR / "src" / "eventData.ts")
    print("Generated → packages/game-state-npm/src/eventData.ts", file=sys.stderr)

    if variant_types:
        generate_ts_variant_types(variant_types, out_path=NPM_GAME_STATE_DIR / "src" / "variantTypes.ts")
        print("Generated → packages/game-state-npm/src/variantTypes.ts", file=sys.stderr)

    _write_ts_index(NPM_GAME_STATE_DIR / "src" / "index.ts", ["models", "eventData", "variantTypes"])


if __name__ == "__main__":
    main()
