#!/usr/bin/env python3
"""data/game_logic_constants.yaml から各言語の定数モジュールを生成する。

ADR-034 Phase 2 で API 契約系の SSoT は data/openapi.yaml + oapi-codegen/NSwag/openapi-typescript
に移行したが、ゲームロジック定数は ADR-034 scope 外として現行の独自 codegen を維持する。

Inputs:
  - data/game_logic_constants.yaml  (Phase / WinReason / EventType 等)

Outputs:
  - packages/game-logic-constants-go/constants_gen.go     (package game_logic)
  - packages/game-logic-constants-dotnet/GameLogicConstants_gen.cs (namespace OverloadParty.GameLogicConstants)
  - packages/game-logic-constants-npm/src/index.ts
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
PACKAGES_DIR = ROOT / "packages"

GAME_LOGIC_YAML = DATA_DIR / "game_logic_constants.yaml"
GO_OUT = PACKAGES_DIR / "game-logic-constants-go" / "constants_gen.go"
DOTNET_OUT = PACKAGES_DIR / "game-logic-constants-dotnet" / "GameLogicConstants_gen.cs"
NPM_OUT = PACKAGES_DIR / "game-logic-constants-npm" / "src" / "index.ts"

GENERATED_HEADER = "// Code generated by scripts/generate_constants.py; DO NOT EDIT."

# (yaml_key, go_prefix, go_comment, cs_class, ts_const, ts_type, extra_union)
GAME_LOGIC_SIMPLE = [
    ("phases", "Phase", "Phases", "Phases", "PHASES", "GamePhase", "'selecting'"),
    ("game_status", "GameStatus", "Game status", "GameStatus", "GAME_STATUS", "GameStatus", None),
    ("win_reasons", "WinReason", "Win reasons", "WinReasons", "WIN_REASONS", "WinReason", None),
    ("action_types", "ActionType", "Action types", "ActionTypes", "ACTION_TYPES", "GameActionType", None),
    ("event_types", "EventType", "Event types", "EventTypes", "EVENT_TYPES", "EventType", None),
    ("effect_durations", "EffectDuration", "Effect durations", "EffectDurations", "EFFECT_DURATIONS", "EffectDuration", None),
    ("trigger_types", "TriggerType", "Trigger types", "TriggerTypes", "TRIGGER_TYPES", "TriggerType", None),
    ("effect_ops", "EffectOp", "Effect operations", "EffectOps", "EFFECT_OPS", "EffectOp", None),
    ("buff_types", "BuffType", "Buff types", "BuffTypes", "BUFF_TYPES", "BuffType", None),
    ("buff_modes", "BuffMode", "Buff modes", "BuffModes", "BUFF_MODES", "BuffMode", None),
    ("custom_effects", "CustomEffect", "Custom effects", "CustomEffects", "CUSTOM_EFFECTS", "CustomEffect", None),
    ("effect_categories", "EffectCategory", "Effect categories", "EffectCategories", "EFFECT_CATEGORIES", "EffectCategory", None),
    ("effect_target_types", "EffectTargetType", "Effect target types", "EffectTargetTypes", "EFFECT_TARGET_TYPES", "EffectTargetType", None),
    ("player_refs", "PlayerRef", "Player references", "PlayerRefs", "PLAYER_REFS", "PlayerRef", None),
    ("use_limits", "UseLimit", "Use limits", "UseLimits", "USE_LIMITS", "UseLimit", None),
    ("guard_types", "GuardType", "Guard types", "GuardTypes", "GUARD_TYPES", "GuardType", None),
    ("selector_pick_modes", "SelectorPickMode", "Selector pick modes", "SelectorPickModes", "SELECTOR_PICK_MODES", "SelectorPickMode", None),
]


def _to_pascal(value: str) -> str:
    value = value.replace("/", "")
    if "_" in value or "-" in value:
        return "".join(w.title() for w in value.replace("-", "_").split("_"))
    if value and value[0].isupper():
        return value
    return value.title() if value else value


def _write_file(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


def _go_const_block(comment: str, prefix: str, values: list[str]) -> list[str]:
    lines = [f"// {comment}.", "const ("]
    for v in values:
        lines.append(f'\t{prefix}{_to_pascal(v)} = "{v}"')
    lines.append(")")
    lines.append("")
    return lines


def _cs_static_class(class_name: str, values: list[str], indent: str = "    ") -> list[str]:
    lines = [f"public static class {class_name}", "{"]
    for v in values:
        lines.append(f'{indent}public const string {_to_pascal(v)} = "{v}";')
    lines.append("}")
    lines.append("")
    return lines


def _ts_const_array(const_name: str, type_name: str, values: list[str], *, extra_union: str | None = None) -> list[str]:
    lines = [f"export const {const_name} = {json.dumps(values)} as const;"]
    if extra_union:
        lines.append(f"export type {type_name} = (typeof {const_name})[number] | {extra_union};")
    else:
        lines.append(f"export type {type_name} = (typeof {const_name})[number];")
    lines.append("")
    return lines


def generate_go(data: dict) -> None:
    lines = [GENERATED_HEADER, "", "package game_logic", ""]
    for yaml_key, prefix, comment, _, _, _, _ in GAME_LOGIC_SIMPLE:
        values = data.get(yaml_key)
        if values is None:
            raise KeyError(f"data/game_logic_constants.yaml is missing required key {yaml_key!r}")
        lines.extend(_go_const_block(comment, prefix, values))
    _write_file(GO_OUT, lines)


def generate_csharp(data: dict) -> None:
    lines = [GENERATED_HEADER, "", "namespace OverloadParty.GameLogicConstants;", ""]
    for yaml_key, _, _, cs_class, _, _, _ in GAME_LOGIC_SIMPLE:
        values = data.get(yaml_key)
        if values is None:
            raise KeyError(f"data/game_logic_constants.yaml is missing required key {yaml_key!r}")
        lines.extend(_cs_static_class(cs_class, values))
    _write_file(DOTNET_OUT, lines)


def generate_ts(data: dict) -> None:
    lines = [GENERATED_HEADER, ""]
    for yaml_key, _, _, _, ts_const, ts_type, extra_union in GAME_LOGIC_SIMPLE:
        values = data.get(yaml_key)
        if values is None:
            raise KeyError(f"data/game_logic_constants.yaml is missing required key {yaml_key!r}")
        lines.extend(_ts_const_array(ts_const, ts_type, values, extra_union=extra_union))
    _write_file(NPM_OUT, lines)


def main() -> int:
    data = yaml.safe_load(GAME_LOGIC_YAML.read_text(encoding="utf-8"))
    generate_go(data)
    generate_csharp(data)
    generate_ts(data)
    print(f"Generated → {GO_OUT.relative_to(ROOT)}", file=sys.stderr)
    print(f"Generated → {DOTNET_OUT.relative_to(ROOT)}", file=sys.stderr)
    print(f"Generated → {NPM_OUT.relative_to(ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
