// Code generated by generate_from_yaml.py from data/constants.json; DO NOT EDIT.

package constants

// Phase constants.
const (
	PhaseDraw = "draw"
	PhaseMain = "main"
	PhaseBattle = "battle"
	PhaseEnd = "end"
)

// Rank constants.
const (
	RankSmall = "small"
	RankMedium = "medium"
	RankLarge = "large"
)

// Instance Family constants.
const (
	FamilyM = "M" // Balanced
	FamilyC = "C" // Compute-optimized (TP×1.3, AV×0.7)
	FamilyR = "R" // Reliability-optimized (TP×0.7, AV×1.3)
)

// Initial game values.
const (
	InitialBudget   = 5000
	InitialInsightPool = 0
	InitialHand     = 5
	HandLimit       = 6
	InitialTimeBank = 480 // seconds (8 minutes)
	MaxAttachments  = 2   // max attachment slots per resource
	SlotsPerZone    = 3   // number of slots per zone
)

// Deck size.
const (
	DeckSize = 30
)

// Game status constants.
const (
	GameStatusWaiting = "waiting" // Waiting for starting resource selection
	GameStatusPlaying = "playing" // Game in progress
	GameStatusFinished = "finished" // Game ended
)

// Win reason constants.
const (
	WinReasonBudgetZero = "budget_zero"
	WinReasonSystemDown = "system_down"
	WinReasonRepositoryOut = "repository_out"
	WinReasonTimeout = "timeout"
	WinReasonDisconnect = "disconnect"
	WinReasonTurnLimit = "turn_limit"
	WinReasonDraw = "draw"
	WinReasonLaunchFailure = "launch_failure"
)

// Faction constants.
const (
	FactionSHE = "SHE"
	FactionTenki = "Tenki"
	FactionSugar = "Sugar"
	FactionTuners = "Tuners"
	FactionNeutral = "Neutral"
)

// Zone constants.
const (
	ZoneFrontend = "frontend"
	ZoneBackend = "backend"
	ZoneSupport = "support"
)

// Action type constants.
const (
	ActionPlayCard = "play_card"
	ActionAttack = "attack"
	ActionScaleUp = "scale_up"
	ActionDistributeYield = "distribute_yield"
	ActionDiscardHand = "discard_hand"
	ActionActivateEffect = "activate_effect"
	ActionSetReactive = "set_reactive"
	ActionMigrate = "migrate"
	ActionEndPhase = "end_phase"
)

// Event type constants.
const (
	EventPlayCard = "play_card"
	EventAttachCard = "attach_card"
	EventAttack = "attack"
	EventScaleUp = "scale_up"
	EventDistributeYield = "distribute_yield"
	EventDiscardHand = "discard_hand"
	EventActivateEffect = "activate_effect"
	EventTrapRevealed = "trap_revealed"
	EventMigrate = "migrate"
	EventMigrationComplete = "migration_complete"
	EventPhaseChange = "phase_change"
	EventPhaseEnd = "phase_end"
	EventTurnEnd = "turn_end"
	EventGameOver = "game_over"
)

// WS message type constants (server → client).
const (
	WSMsgGameState = "game_state"
	WSMsgGameOver = "game_over"
	WSMsgError = "error"
	WSMsgGameEntered = "game_entered"
	WSMsgMatchmakingStarted = "matchmaking_started"
	WSMsgMatchmakingCancelled = "matchmaking_cancelled"
	WSMsgActionRejected = "action_rejected"
	WSMsgStampUsed = "stamp_used"
	WSMsgPong = "pong"
	WSMsgMatchFound = "match_found"
	WSMsgGameStateRestore = "game_state_restore"
	WSMsgActionPerformed = "action_performed"
	WSMsgTurnControls = "turn_controls"
	WSMsgNpcBattleCreated = "npc_battle_created"
)

// WS message type constants (client → server).
const (
	WSMsgGameEnter = "game_enter"
	WSMsgMatchmakingStart = "matchmaking_start"
	WSMsgMatchmakingCancel = "matchmaking_cancel"
	WSMsgGameAction = "game_action"
	WSMsgUseStamp = "use_stamp"
	WSMsgPing = "ping"
	WSMsgNpcBattleStart = "npc_battle_start"
)
